### ISSUE TITLE
Invalid header value char on ozon.ru

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe-hammerhead#2319] opened 2020-05-18 07:59 UTC
```js
import { Selector } from 'testcafe';

fixture `ozon.ru`
    .page `ozon.ru`;

test('New Test', async t => {
    await t
        .click(Selector('body'));
});
```
### Your Environment details:

* node.js version:                    `12.8.1`
* browser name and version: `chrome`
* platform and version:          `win 7`

**Comment by LavrovArtem** [comment] 2020-05-18 08:25
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/2188

**Closed by LavrovArtem** 2020-05-18 08:25 UTC
Labels: REASON: duplicate
