### ISSUE TITLE
Should handle case when origin server respond with invalid character in header content

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1402] opened 2017-12-05 08:20 UTC
http://www.ctrip.com
Reproduced not stable.

Simple example to reproduce:
```js
var http = require('http');
var fs   = require('fs');

http.createServer(function (req, res) {
    var content = '';

    if (req.url === '/')
        content = fs.readFileSync('index.html');
    else if (req.url === '/wrong-header') {
        res.setHeader('200', 'あ');
    }


    res.end(content);
}).listen(3000);
```

Internal links
http://ccnet.devexpress.devx/ccnet/server/farm/project/TESTCafe+Health+Monitor+(hammerhead_git)/build/log20171204220012.xml/ViewBuildLog.aspx
http://ccnet.devexpress.devx/ccnet/server/farm/project/TESTCafe+Health+Monitor+(hammerhead_git)/build/log20171201220003.xml/ViewBuildLog.aspx
http://ccnet.devexpress.devx/ccnet/server/farm/project/TESTCafe+Health+Monitor+(hammerhead_git)/build/log20171127220003.xml/ViewBuildLog.aspx

**Comment by LavrovArtem** [comment] 2020-02-10 14:35
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/2188

**Closed by LavrovArtem** 2020-02-10 14:35 UTC
Labels: AREA: server, TYPE: enhancement, health-monitor
