### ISSUE TITLE
 Uncaught SyntaxError: Missing initializer in const declaration after uprading from 1.8.6 to 1.8.7

### ISSUE THREAD

**Issue by franciscolosardo** [DevExpress/testcafe-hammerhead#2368] opened 2020-06-26 18:23 UTC
### What is your Scenario?

 We were testing our app without problems until 1.8.7 showed up.
### What is the Current behavior?

 Now our element Console in the webpage doesn't load properly , we believe its a problem with a console error that is thrown when loading our page.
The following syntax error is thrown on our script mounted through testcafe's hammerhead
```
Uncaught SyntaxError: Missing initializer in const declaration
```

I would love to send the minified file with the error to the dev team, but i can't display it publicly.

### What is the Expected behavior?

 This script should load normally as it did up until 1.8.6

### Your Environment details:

* node.js version:    12                 
* browser name and version: Chrome 81
* platform and version:   MacOS       
* other:                                   
* testcafe version :( 1.8.7) , 1.8.6 worked fine

**Comment by LavrovArtem** [comment] 2020-06-29 09:44
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/2363

**Closed by LavrovArtem** 2020-06-29 09:44 UTC
Labels: REASON: duplicate, STATE: Need response
