### ISSUE TITLE
Authentication causes Angular's change detection to stop working only in Hammerhead

### ISSUE THREAD

**Issue by Tommy228** [DevExpress/testcafe-hammerhead#2134] opened 2019-09-07 09:03 UTC
Hi. 

This is a very specific issue, however it is blocker and prevents using TestCafé.

### What is your Scenario?
Provided you are using Angular and [Auth0](https://auth0.com/) to handle your authentication.
* Open your website using Hammerhead
* Authenticate
* Try to perform tasks which require Angular to detect changes

### What is the Current behavior?
For some reason, the authentication causes Angular's automatic change detection to stop working.

**This only happens when opening the website with Hammerhead (and obviously, running TestCafé tests)**. 

This means that the application's displayed state does not change, preventing e2e tests to work. 
 
### What is the Expected behavior?
Working change detection when authenticating and using Hammerhead.
 
### What is your public web site URL?
https://tommy228.github.io/

Your complete app code (or attach your test files):
* Source code: https://github.com/Tommy228/testcafe-auth-bug
* [Authentication Service](https://github.com/Tommy228/testcafe-auth-bug/blob/master/src/app/auth.service.ts)
* [Authentication Guard](https://github.com/Tommy228/testcafe-auth-bug/blob/master/src/app/auth.guard.ts)
* [Main Component](https://github.com/Tommy228/testcafe-auth-bug/blob/master/src/app/main/main.component.ts)
</details>

### Steps to Reproduce:
1. Go to: https://tommy228.github.io/
2. Authenticate using any GitHub credentials
3. Try to update the displayed value by clicking the "Toggle" button. If you are using Hammerhead, it will not update.
 
### Your Environment details:

* node.js version: 10.16.0
* browser name and version: Chrome 76
* platform and version: Windows
* other: using the latest stable versions of Angular, [auth0-js](https://github.com/auth0/auth0.js) and TestCafé.

Thank you for your time.

**Comment by miherlosev** [comment] 2019-09-09 09:55
Hi @Tommy228 

Thank you for the provided example. I've reproduced the problem.

**Comment by LavrovArtem** [comment] 2019-09-10 13:14
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1902

**Closed by LavrovArtem** 2019-09-10 13:14 UTC
Labels: STATE: Need research, TYPE: bug
