### ISSUE TITLE
"getElementsByTagName" method returns collection with extra properties

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#1172] opened 2017-06-08 19:18 UTC
Based on 
https://testcafe-discuss.devexpress.com/t/uncaught-typeerror-elm-getattribute-is-not-a-function/304

There are two extra methods `item` and `namedItem` in the `for ... in` loop.

Check all errors on this site.

**Comment by miherlosev** [comment] 2017-06-09 09:30
I'm working on this

**Comment by miherlosev** [comment] 2017-06-09 09:31
Page for reproduce - http://start.att.net

**Comment by LavrovArtem** [comment] 2017-06-09 09:37
duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1141

**Comment by miherlosev** [comment] 2017-06-09 09:46
I've reproduce an another problem:
```js
Uncaught TypeError: Illegal invocation
    at ShadowUI.getRoot (http://localhost:1401/hammerhead.js:10511:59)
    at Object.set (http://localhost:1401/hammerhead.js:2328:68)
    at value (http://localhost:1401/hammerhead.js:2983:183)
....
```

**Comment by LavrovArtem** [comment] 2017-06-09 11:05
The last problem is regression of https://github.com/DevExpress/testcafe-hammerhead/pull/1150

**Comment by miherlosev** [comment] 2017-06-16 14:23
Aftex fix regression, I've the origin problem.

`item` and `namedItem` are placed in `HTMLCollection` prototype.
We use an `Array` to filter `shadowUI` items and put `item` and `namedItem` directly to result object.

The simple example to reproduce:
```js
<html>
	<body>
		<script></script>
		<script>
			var nodeList = document.getElementsByTagName('script');
			
                        // Without proxing these statements log the 'false' value
                        // With proxing - 'true'
			console.log(nodeList.hasOwnProperty('item'));
			console.log(nodeList.hasOwnProperty('namedItem'));
		</script>
	</body>
</html>
```

**Closed** 2017-06-23 11:51 UTC
Labels: !IMPORTANT!, API MODIFICATION LEVEL: non-breaking changes, AREA: client, TYPE: bug
