### ISSUE TITLE
Unhandled promise rejection - Error [ERR_HTTP_TRAILER_INVALID]: Trailers are invalid with this transfer encoding

### ISSUE THREAD

**Issue by kacy-weakley** [DevExpress/testcafe-hammerhead#2692] opened 2021-09-20 18:27 UTC
### What is your Scenario?
We have a whole test suite that began failing this weekend, due to an unhandled promise rejection - ERR_HTTP_TRAILER_INVALID error. The tests previously were passing for quite some time, running against headless Chromium browser. 

### What is the Current behavior?
The tests, intermittently, are making it all the way to the end of the test and then fail on closing, with the following error:
```
1) Unhandled promise rejection:
      
      Error [ERR_HTTP_TRAILER_INVALID]: Trailers are invalid with this transfer encoding
      at ServerResponse._storeHeader (_http_outgoing.js:445:11)
      at ServerResponse.writeHead (_http_server.js:312:8)
      at RequestPipelineContext.sendResponseHeaders (/Volumes/casesensitive/git/mc_testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/context.js:319:13)
      at Array.sendProxyResponse (/Volumes/casesensitive/git/mc_testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/stages.js:129:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Object.run (/Volumes/casesensitive/git/mc_testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/index.js:19:9)
```
 
### What is the Expected behavior?
Tests pass consistently.
 
### What is your public web site URL?

Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
 This is a simple test as an example:
```js
import {Selector, t} from "testcafe";

const username = Selector("#username");
const password = Selector("#password");
const btnLogin = Selector("button[value='log in']");
const recoverPwdMsg = Selector("div[class='feedback-block error section']");

async function login(user, pwd) {
    await t
      .typeText(username, user)
      .typeText(password, pwd)
      .click(btnLogin);
}

fixture`Mailchimp User Signin Tests`;

test.page`https://mailchimp.com/login`(
  "Signin with invalid user credentials: Invalid User: @login",
  async t => {
    await t.expect(username.exists).ok();
    await login("abc12345!", "abc12345!");
    await t.expect(recoverPwdMsg.exists).ok();
  }
);
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to: https://mailchimp.com/login
2. Execute this command: Enter invalid credentials and click login
3. See the error: Test steps and assertions complete successfully but test reports failure due to unhandled promise rejection.
 
### Your Environment details:

* node.js version:                     v14.17.2
* browser name and version: Chrome 92.0.4479.0 (92.0.4515.159 / Linux 0.0 in Jenkins)
* platform and version:          macOS 10.15.7 (as well as Linux in Jenkins)
* other:                                   Have been using Testcafe 1.14.2. Issue also seen on 1.15.0. Unable to upgrade to latest Testcafe version due to outstanding iframe issues.

**Comment by dineshk-qa** [comment] 2021-09-21 04:19
Same here, our tests were passing earlier but now getting this error on majority of tests there.
Look like something to do with parsing header text?

**Comment by vibecode** [comment] 2021-09-21 08:37
We started to have the same issue recently.

node:  node: '12.22.4'
Chrome 93.0.4577.82 / Linux 0.0
Testcafe: initially seen on 1.9.4  and the same after upgrade to 1.16.0

**Comment by Dmitry-Ostashev** [comment] 2021-09-21 08:52
@kacy-weakley @dineshk-qa  Thank you for your reports.

Try to install TestCafe v1.15.3 or later and set the [disableHttp2](https://testcafe.io/documentation/402638/reference/configuration-file#disablehttp2) configuration option to disable support for HTTP/2 requests. I checked it on my side, and the error has gone.

**Comment by neekfenwick** [comment] 2021-09-21 09:14
> Try to install TestCafe v1.15.3 or later and set the [disableHttp2](https://testcafe.io/documentation/402638/reference/configuration-file#disablehttp2) configuration option to disable support for HTTP/2 requests. I checked it on my side, and the error has gone.

I've started seeing a changing number of my 55 tests fail since 18th Sept, sometimes 6, 20, 4 or 8 tests. Our yum.log indicates chrome was updated to google-chrome-stable-93.0.4577.82-1.x86_64 on 14th Sept but I don't see a correlation with this TestCafe issue.

Running with TestCafe v1.15.3 and "--disable-http2" does not fix the error. I've no idea how to investigate it further.

I used `--disable-http2` rather than a config file because when I create a .testcaferc.json with `{ "disableHttp2": true }` I get "The "filter" option from the configuration file will be ignored." in the output, which is weird.  Removing the file gives no such output.

**Comment by AKK9** [comment] 2021-09-21 10:51
We're experiencing the same issue, only started happening about 18 hours ago. Our browser versions are the same between our successful and failed runs. Was running on Node 12, and TestCafe 1.8.8.

Upgrading to Node 14 and TestCafe 1.16.0 has not helped.

Node v12 and v14
Chrome 93.0.4577.63 / Windows 10 in GitLab CI
TestCafe 1.16.0

Disabling HTTP/2, via a `.testcaferc.json` with the following content, did not help:
```
{ "disableHttp2": true }
```

**Comment by kacy-weakley** [comment] 2021-09-21 14:00
> @kacy-weakley @dineshk-qa Thank you for your reports.
> 
> Try to install TestCafe v1.15.3 or later and set the [disableHttp2](https://testcafe.io/documentation/402638/reference/configuration-file#disablehttp2) configuration option to disable support for HTTP/2 requests. I checked it on my side, and the error has gone.

I've tried updating to v1.15.3 and to v1.16.0, both with the `disableHttp2` option applied, but the error still persists.

**Comment by Dmitry-Ostashev** [comment] 2021-09-22 08:13
Thank you all for the information. We will research it and update this thread once we have any news.

**Comment by Awatatah** [comment] 2021-09-22 17:28
+1

**Comment by Asuza** [comment] 2021-09-22 21:58
This same issue is occurring for me even when using TestCafe v1.16.0 with the `--disable-http2` flag. I also tried using the flag in the testcaferc file and it didn't help there, either.

**Comment by aks-** [comment] 2021-09-23 07:34
Has anyone yet tried to downgrade chrome in their pipeline or sth and checked if this works? `--disable-http2` wouldnt' work if chrome has updated something and it seems to be coming from there 🤔

**Comment by smolnikov** [comment] 2021-09-23 15:35
This is also reproduced for me both:

- on local machine with MacOS 11.4, Testcafe 1.8.1, node v10.24.1, Chrome 93.0.4577.82 
- on Jenkins with node:10-apline, Testcafe 1.8.1, node v10.24.1, Chrome 81.0.4044.138 / Linux 0.0

**Comment by aks-** [comment] 2021-09-23 16:17
Issue also appears on Ubuntu  20.04.3, Testcafe 1.16 and 1.14, node v16,  Firefox 92.0 with and without `--disable-http2` flag

**Comment by rhowk** [comment] 2021-09-23 16:57
1) Unhandled promise rejection:

   Error [ERR_HTTP_TRAILER_INVALID]: Trailers are invalid with this transfer encoding
   at ServerResponse._storeHeader (_http_outgoing.js:473:11)
   at ServerResponse.writeHead (_http_server.js:328:8)
   at RequestPipelineContext.sendResponseHeaders (/home/ec2-user/elc-ui-testing/node_modules/testcafe-hammerhead/lib/request-pipeline/context.js:343:9)
   at Array.sendProxyResponse (/home/ec2-user/elc-ui-testing/node_modules/testcafe-hammerhead/lib/request-pipeline/index.js:137:7)
   at runMicrotasks ((anonymous→)
   at processTicksAndRejections (internal/process/task_queues.js:93:5)
   at run (/home/ec2-user/elc-ui-testing/node_modules/testcafe-hammerhead/lib/request-pipeline/index.js:161:5)

   Browser: Chrome 87.0.4280.88 / Linux 0.0
   
Node 14.16

on both linux server and local mac. Our tests go through to the end but error is reported in the final report, so we end up with a test that actually passed all its steps, and shows as failing.

**Comment by JIGD** [comment] 2021-09-27 04:46
Same issue here:    
2) Unhandled promise rejection:

      Error [ERR_HTTP_TRAILER_INVALID]: Trailers are invalid with this transfer encoding
      at new NodeError (node:internal/errors:363:5)
      at ServerResponse._storeHeader (node:_http_outgoing:488:11)
      at ServerResponse.writeHead (node:_http_server:348:8)
      at RequestPipelineContext.sendResponseHeaders (C:\Users\korn1\OneDrive\Documentos\GitHub\ek-autotests\node_modules\testcafe-hammerhead\lib\request-pipeline\context.js:321:13)
      at Array.sendProxyResponse (C:\Users\korn1\OneDrive\Documentos\GitHub\ek-autotests\node_modules\testcafe-hammerhead\lib\request-pipeline\stages.js:129:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Object.run (C:\Users\korn1\OneDrive\Documentos\GitHub\ek-autotests\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:19:9)

**Comment by neekfenwick** [comment] 2021-09-27 05:06
I see there is a possible fix in https://github.com/ProdPerfect/testcafe-hammerhead/pull/4 mentioned above by rhymiz.. can we mere mortals get this into our environments or is it best we wait for a new Testcafe release that would include the fix?  I'm personally pulling it via npm with `testcafe": "^1.15.2"` in my package.json.

**Comment by karimelkomy** [comment] 2021-09-27 10:24
hey team, any update here about releasing the ^ fix, it is a blocking issue for us which cause a lot of random failures

**Comment by rhowk** [comment] 2021-09-27 18:36
so this is a complete hack, use at your own risk, but we were already intercepting the report json and adding some metadata to it to "customize" our reports. So to get around this issue we basically tested to see if the status was "failed" and then searched for the particular error message in the steps:
`const reportsData = reportFiles.reduce((files, reportFile) => {
      let revisedMetadata = {};

      if (isJson(reportFile)) {
        const reportJSON = getReport(reportFile);
        const [reportFields] = reportJSON;
        const [, domainFromReport = ''] = reportFields.metadata.app.name.split('-');
        const { status = '', steps } = reportFields.elements[0];

        // @todo this is temporary, delete as soon as testcafe is not reporting this error.
        if (status === 'failed'){
          let stepIteration = 0
          steps.forEach(function(step) {
            const errorMsg = step.result.error_message;
            if (errorMsg.indexOf('ERR_HTTP_TRAILER_INVALID') !== -1){
              logger.log('bad error! delete this step!')
              delete reportFields.elements[0].steps[stepIteration].result.error_message;
              reportFields.elements[0].steps[stepIteration].result.status = "passed";
              reportFields.elements[0].status = 'passed'
              stepIteration ++;
            }
          });
        }

        const metadatum = metaData[domainFromReport];

        if (metadatum && status === 'passed') {
          logger.log(`Combining data from (${domainFromReport})`);
          revisedMetadata = metadatum.map(mapMetaData);
        }

        reportJSON[0].metadata = { ...metadatum, ...revisedMetadata };
        const filename = join(dirs.modifiedReportDir, `${domainFromReport}.json`);
        files.push({ filename, revisedReport: reportJSON });
      }
      return files;
    }, []);`
    
    Again, this is nothing but a temp workaround for us, but if it helps someone get over the hump...

**Comment by JoniVanderheijden** [comment] 2021-09-27 22:39
If you're one of those poor sods pulling this issue in through Testcafe and aren't against using patch-package. This is the patch file that fixed it for us until testcafe pulls in the fix.

/patches/testcafe++testcafe-hammerhead+24.5.1.patch
```
diff --git a/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/builtin-header-names.js b/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/builtin-header-names.js
index 4762b6f..b7249df 100644
--- a/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/builtin-header-names.js
+++ b/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/builtin-header-names.js
@@ -32,6 +32,7 @@ exports.default = {
     accept: 'accept',
     contentEncoding: 'content-encoding',
     expires: 'expires',
+    trailer: 'trailer',
     serviceWorkerAllowed: 'service-worker-allowed',
     accessControlAllowOrigin: 'access-control-allow-origin',
     accessControlAllowCredentials: 'access-control-allow-credentials',
diff --git a/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/header-transforms/transforms.js b/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/header-transforms/transforms.js
index 7c2303d..d8eb2db 100644
--- a/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/header-transforms/transforms.js
+++ b/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/header-transforms/transforms.js
@@ -97,6 +97,7 @@ exports.forcedRequestTransforms = {
 };
 // Response headers
 exports.responseTransforms = {
+    [builtin_header_names_1.default.trailer]: skip,
     // NOTE: Disable Content Security Policy (see http://en.wikipedia.org/wiki/Content_Security_Policy).
     [builtin_header_names_1.default.contentSecurityPolicy]: skip,
     [builtin_header_names_1.default.contentSecurityPolicyReportOnly]: skip,
```

**Comment by Dmitry-Ostashev** [comment] 2021-09-28 08:49
@JoniVanderheijden  Thank you for your workaround.
@karimelkomy  We cannot give exact estimates when the fix will be released. Please stay tuned.

**Closed** 2021-09-30 09:18 UTC
Labels: TYPE: bug, SYSTEM: pipeline, AREA: server, FREQUENCY: critical
