### ISSUE TITLE
Internal Event Listeners do not work with the ASPxSpreadsheet control

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe-hammerhead#2194] opened 2019-12-10 13:57 UTC
See the initial issue: https://github.com/DevExpress/testcafe-studio/issues/2881.

Steps to reproduce:

1. 1. Run the ASPxSpreadsheet demo with the Hammerhead proxy:[https://demos.devexpress.com/ASPxSpreadsheetDemos/Features/DocumentManagement.aspx](https://demos.devexpress.com/ASPxSpreadsheetDemos/Features/DocumentManagement.aspx);

2. Focus any cell;
3. Open DevTools, find an <iframe> element, focus on it
4. Check the iframe document event listeners:

`getEventListeners(document)`

There wouldn't be any internal listener.

5. Try to add an internal listener using the following code:

`window["%hammerhead%"].eventSandbox.listeners.addInternalEventListener(document, ['keydown'], (ev) => console.log(ev));`

Enter some characters in any cell. The Console will remain empty.

**Comment by LavrovArtem** [comment] 2019-12-19 12:25
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1881

**Closed by LavrovArtem** 2019-12-19 12:25 UTC
Labels: TYPE: bug, support center
