### ISSUE TITLE
Cant open Login page when opend with testcafe

### ISSUE THREAD

**Issue by nao3301** [DevExpress/testcafe-hammerhead#2391] opened 2020-07-24 09:11 UTC
### What is your Test Scenario?
If i open the Login page by url, everthing works fine. If testcafe opens the page there is an error and it does not load.
 
### What is the current behavior?
when the test starts the opened window shows just loading spinner and the console output says :
:55579/h5ycmw2PF!s!utf-8/http://localhost:4200/vendor.js:177380 Uncaught SyntaxError: Unexpected token ';'

 
### What is the Expected behavior?
no error and login page loads 
 
### What is your web application and your TestCafe test code?

its an angular SPA

test.ts
```js
 
fixture('password-module')
    .disablePageCaching
    .page(baseUrl)

// Single test to check login functionality
test('login', async t => {
    const getLocation = ClientFunction(() => document.location.href)
    await t
    .useRole(roles.admin.role)
     .expect(getLocation()).contains('password')
})


```

roles.ts 

```js
import { Role, Selector } from 'testcafe'
import { btn } from './patterns'

const isProd = false

export const baseUrl =  'http://localhost:4200'
export const dBInput = Selector('input').withAttribute('name', 'database')
export const nameInput = Selector('input').withAttribute('name', 'username')
export const passwdInput = Selector('input').withAttribute('name', 'password')

export const roles = {

  admin: {
    role: Role(baseUrl + '/authentication/login', async t => {
      await t
        .maximizeWindow()
        .typeText(dBInput, 'Test')
        .typeText(nameInput, 'TestUser')
        .typeText(passwdInput, 'Testpasswd', { replace: true })
        .click(await btn('Login'))
        .wait(10000)
    }, { preserveUrl: true }
    )
  }
}

```

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
Running tests in:
 - Chrome 84.0.4147.89 / Windows 10

 password-module
 × login
   1) - Error in Role initializer -
      A JavaScript error occurred on "http://localhost:4200/".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      SyntaxError: Unexpected token ';'

      Browser: Chrome 84.0.4147.89 / Windows 10
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

unfortunately is it not possible for you to reproduce :( I'll give my best to get you all the infos you need

the problem is in these lines:

```js

childView.rootNodes.forEach((element) => {
--
  | if (element.nodeType === 1) {
  | this.renderer.addClass(element, DX_TEMPLATE_WRAPPER_CLASS);
  | }
  | Object(devextreme_events__WEBPACK_IMPORTED_MODULE_6__["one"])(element, 'dxremove', ( _hh$temp195 , params) => {
  | var; if (!params \|\| !params._angularIntegration) {
  | childView.destroy();
  | }
  | });
  | });
  | return childView.rootNodes;

```
var; - here is some name missing i guess 
 
### Your Environment details:
 
* testcafe version:    1.8.8               
* node.js version:     v14.2.0               
* command-line arguments: chrome test,ts 
* browser name and version: Chrome 84.0.4147.89 
* platform and version:   Windows 10       
* other:

**Comment by nao3301** [comment] 2020-07-24 10:34
thanks!,
i think its this:
```js
 childView.rootNodes.forEach((element) => {
            if (element.nodeType === 1) {
                this.renderer.addClass(element, DX_TEMPLATE_WRAPPER_CLASS);
            }
            Object(devextreme_events__WEBPACK_IMPORTED_MODULE_6__["one"])(element, 'dxremove', ({}, params) => {
                if (!params || !params._angularIntegration) {
                    childView.destroy();
                }
            });
        });
```

**Comment by Farfurix** [comment] 2020-07-24 14:17
@nao3301 

Thank you for sharing this information. We have an [open PR](https://github.com/DevExpress/testcafe-hammerhead/pull/2389) that fixes a similar issue. Could you please check if this PR fixes all issues in your project by using the steps below?
1. Download the LavrovArtem:empty-destructuring branch (`git clone -b empty-destructuring https://github.com/LavrovArtem/testcafe-hammerhead.git`).
2. Install dependencies (`npm i`).
3. Run `http-playground` (`gulp http-playground`).
4. Enter your URL into the "localhost:1400" browser tab and click "Proxy!".
5. See that there is no "Uncaught SyntaxError..." errors in DevTools.

**Comment by nao3301** [comment] 2020-07-27 09:11
unfortunately this throws some exeptions as well:

```
vendor.js:22245 Uncaught Error: Template parse errors:
Unexpected closing tag "label". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
    <span class="switch-label"></span>
    <span class="switch-handle"></span>
  [ERROR ->]</label> -->
  <div class="d-flex w-100 mto-prevent-selection">
    <div class="mx-auto">
"): ng:///SearchModule/ListOrStructureComponent.html@4:2
    at syntaxError (vendor.js:22245)
    at DirectiveNormalizer._preparseLoadedTemplate (vendor.js:37653)
    at vendor.js:37644
    at Object.then (vendor.js:22236)
    at DirectiveNormalizer._preParseTemplate (vendor.js:37644)
    at DirectiveNormalizer.normalizeTemplate (vendor.js:37631)
    at CompileMetadataResolver.loadDirectiveMetadata (vendor.js:39785)
    at vendor.js:45721
    at Array.forEach (<anonymous>)
    at vendor.js:45720
syntaxError @ vendor.js:22245
_preparseLoadedTemplate @ vendor.js:37653
(anonymous) @ vendor.js:37644
then @ vendor.js:22236
_preParseTemplate @ vendor.js:37644
normalizeTemplate @ vendor.js:37631
loadDirectiveMetadata @ vendor.js:39785
(anonymous) @ vendor.js:45721
(anonymous) @ vendor.js:45720
_loadModules @ vendor.js:45717
_compileModuleAndComponents @ vendor.js:45697
compileModuleAsync @ vendor.js:45659
compileModuleAsync @ vendor.js:96460
compileNgModuleFactory__PRE_R3__ @ vendor.js:82535
bootstrapModule @ vendor.js:82855
./src/main.ts @ main.js:297594
__webpack_require__ @ runtime.js:82
0 @ main.js:297607
__webpack_require__ @ runtime.js:82
checkDeferredModules @ runtime.js:47
webpackJsonpCallback @ runtime.js:34
(anonymous) @ main.js:2
11:08:56.458 DevTools failed to load SourceMap: Could not load content for chrome-extension://gnldpbnocfnlkkicnaplmkaphfdnlplb/ContentScript/CustomisedWorkItemMessaging.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
11:08:56.459 DevTools failed to load SourceMap: Could not load content for chrome-extension://gnldpbnocfnlkkicnaplmkaphfdnlplb/ContentScript/CaptureBrowserEvent.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
11:08:56.608 Grammarly.js:2 [DEFAULT]: WARN : Using DEFAULT root logger
t.printToConsole @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
t.logImpl @ Grammarly.js:2
e.log @ Grammarly.js:2
e.warn @ Grammarly.js:2
e.getRootLogger @ Grammarly.js:2
get @ Grammarly.js:2
e.getLogger @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
11:08:56.617 Grammarly.js:2 [WARNING] Using default timeseries implementation.
e.getRootMetric @ Grammarly.js:2
e @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
t.pipe @ Grammarly.js:2
e.rootLogLevelGetter @ Grammarly.js:2
u @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
11:08:56.634 VM6861:1 Uncaught SyntaxError: Unexpected token ')'
    at exports.parse (hammerhead.js:8851)
    at Function._getMessageData (hammerhead.js:13644)
    at MessageSandbox._onMessage (hammerhead.js:13661)
    at fastApply (hammerhead.js:24905)
    at onMessageHandler (hammerhead.js:13741)
    at hammerhead.js:13297
exports.parse @ hammerhead.js:8851
_getMessageData @ hammerhead.js:13644
_onMessage @ hammerhead.js:13661
fastApply @ hammerhead.js:24905
onMessageHandler @ hammerhead.js:13741
(anonymous) @ hammerhead.js:13297
postMessage (async)
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
Show 10 more frames
11:08:56.635 VM6862:1 Uncaught SyntaxError: Unexpected token ')'
    at exports.parse (hammerhead.js:8851)
    at Function._getMessageData (hammerhead.js:13644)
    at MessageSandbox._onWindowMessage (hammerhead.js:13677)
    at fastApply (hammerhead.js:24896)
    at onWindowMessageHandler (hammerhead.js:13749)
    at hammerhead.js:13242
exports.parse @ hammerhead.js:8851
_getMessageData @ hammerhead.js:13644
_onWindowMessage @ hammerhead.js:13677
fastApply @ hammerhead.js:24896
onWindowMessageHandler @ hammerhead.js:13749
(anonymous) @ hammerhead.js:13242
postMessage (async)
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
n @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
(anonymous) @ Grammarly.js:2
Show 10 more frames
11:08:56.649 hammerhead.js:11154 [WDS] Live Reloading enabled.
```

**Comment by miherlosev** [comment] 2020-07-27 11:39
Hi @nao3301 

This error is caused by the 'Grammarly' browser extension. TestCafe uses a custom browser profile, and this error does not affect TestCafe.

I reviewed the error stack, and I see that this issue was fixed in the custom build. We are going to release a new TestCafe version after the [PR](https://github.com/DevExpress/testcafe-hammerhead/pull/2389) is merged.

**Comment by nao3301** [comment] 2020-07-27 15:27
this one ist not. it is still there if grammarly is deactivated.

```
vendor.js:22245 Uncaught Error: Template parse errors:
Unexpected closing tag "label". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
    <span class="switch-label"></span>
    <span class="switch-handle"></span>
  [ERROR ->]</label> -->
  <div class="d-flex w-100 mto-prevent-selection">
    <div class="mx-auto">
"): ng:///SearchModule/ListOrStructureComponent.html@4:2
    at syntaxError (vendor.js:22245)
    at DirectiveNormalizer._preparseLoadedTemplate (vendor.js:37653)
    at vendor.js:37644
    at Object.then (vendor.js:22236)
    at DirectiveNormalizer._preParseTemplate (vendor.js:37644)
    at DirectiveNormalizer.normalizeTemplate (vendor.js:37631)
    at CompileMetadataResolver.loadDirectiveMetadata (vendor.js:39785)
    at vendor.js:45721
    at Array.forEach (<anonymous>)
    at vendor.js:45720
```

**Comment by Farfurix** [comment] 2020-07-28 09:40
@nao3301

Hello,

This information is not sufficient to determine the cause of this issue. We need to examine some minimal project that uses this "vendor.js" code. Could you please share it with us?

**Comment by nao3301** [comment] 2020-07-28 12:09
so this was an error caused by us. This could we fix. Thanks for your help!!!

**Closed** 2020-07-28 12:20 UTC
Labels: STATE: Need response
