### ISSUE TITLE
[Testing day 0.9.0-rc1] Error raised on page https://jsfiddle.net/ in hammerhead-playground

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#799] opened 2016-09-20 10:03 UTC
For more info see https://github.com/DevExpress/testcafe/issues/826

**Comment by LavrovArtem** [comment] 2016-09-20 13:09
duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/722

**Comment by churkin** [comment] 2016-09-22 11:26
duplicated to #722

**Closed** 2016-09-22 11:27 UTC
Labels: AREA: client, TYPE: bug
