### ISSUE TITLE
Non-proxied script in the Facebook Player example

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#1834] opened 2018-11-14 08:40 UTC
https://github.com/DevExpress/testcafe/issues/3115

The following test throws cross-domain errors from a script with a non-proxied URL:

```js
 import { t, Selector } from 'testcafe';

fixture('FB Video').page(
  'http://developers.facebook.com/docs/plugins/embedded-video-player/'
);

test('example', async () => {
  const fbVideoIframe = Selector(
    'iframe[src*="facebook.com"][title="fb:video Facebook Social Plugin"]'
  );

  await t.hover('h2#how-to-get-a-video-posts-url');

  await t.switchToIframe(fbVideoIframe);
});
```
```
   1) Error on page "https://developers.facebook.com/docs/plugins/embedded-video-player/":

      Permission denied to access property "pathname" on cross-origin object:
      f@https://static.xx.fbcdn.net/rsrc.php/v3/yK/r/32yYfKd5nwi.js:9:528

      Browser: Firefox 61.0.0 / Windows 10.0.0

          7 |test('example', async () => {
          8 |  const fbVideoIframe = Selector(
          9 |    'iframe[src*="facebook.com"][title="fb:video Facebook Social Plugin"]'
         10 |  );
         11 |
       > 12 |  await t.hover('h2#how-to-get-a-video-posts-url');
         13 |
         14 |  await t.switchToIframe(fbVideoIframe);
         15 |});
         16 |
```

**Comment by LavrovArtem** [comment] 2019-02-06 13:53
The cross-domain errors occur because we don't support the [document.domain](https://developer.mozilla.org/en-US/docs/Web/API/Document/domain) property.
This is a duplicate of the #47 issue.

**Closed by LavrovArtem** 2019-02-06 13:53 UTC
Labels: TYPE: bug
