### ISSUE TITLE
Submit from a top window to a frame doesn't work

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#722] opened 2016-08-05 15:44 UTC
Server for reproducing:

``` javascript
var http = require('http');

http.createServer(function(req, res) {
    res.setHeader('content-type', 'text/html')

    switch (req.url) {
        case '/':
            return res.end(`
                <iframe name="iframe_name"></iframe>
                <form action="form.html"></form>
                <script>
                    var iframe = document.querySelector("iframe");
                    var form = document.querySelector("form");

                    var storedTarget = form.target;
                    var storedAction = form.action;

                    form.target = "iframe_name";
                    form.action = "new.html";

                    form.submit();

                    form.target = storedTarget;
                    form.action = storedAction;
                </script>
            `);
        case '/form.html?':
            return res.end('<h1>Fail!!!</h1>');
        case '/new.html?':
            return res.end('<h1>Success!!!</h1>');
        default:
            res.end();
    }
}).listen(5000);
```

**Comment by LavrovArtem** [comment] 2016-09-20 14:46
[temporary solution](https://github.com/DevExpress/testcafe-hammerhead/issues/804)

**Comment by churkin** [comment] 2016-09-22 11:24
We have a few bugs because of this behavior. The error appeared after transitions to promises, due to the fact that the 'pinkie' library implements the asynchronous promises. Using callback is bad, but in this case we have to return them. All this mechanism disappears after https://github.com/DevExpress/testcafe-hammerhead/issues/667 fix.

**Comment by Farfurix** [comment] 2021-04-12 08:17
I didn't manage to reproduce it with Chrome, Firefox, and Windows 10. So, I'll close this issue.

**Closed by Farfurix** 2021-04-12 08:17 UTC
Labels: AREA: client, FREQUENCY: level 1, SYSTEM: URL processing, TYPE: bug
