### ISSUE TITLE
Get rid of Array.prototype/Object.prototype methods in client and shared code

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#245] opened 2015-11-09 11:10 UTC
`Array.prototype.slice.call` is used in many places.
![1](https://cloud.githubusercontent.com/assets/4133518/11030461/3f33d9b6-86df-11e5-96f3-ca6b5d88654b.png)

We need to create cloneItems(iterableObject) util and rewrite all places.
https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments

**Comment by inikulin** [comment] 2015-11-09 11:19
**IMPORTANT**: we shouldn't do this for `arguments`, use inline copy instead

**Comment by inikulin** [comment] 2015-11-09 14:54
We should avoid using native object prototype methods, since they can be overriden by the client code. It would be nice to have some kind of check for this, maybe custom eslint-plugin.

**Comment by inikulin** [comment] 2015-11-09 14:56
@LavrovArtem @miherlosev I've updated the task

**Comment by LavrovArtem** [comment] 2015-11-10 10:55
@inikulin I found this [issue](https://github.com/eslint/eslint/issues/3504) in eslint repo, but it was closed. Plugin I could not find.

**Comment by inikulin** [comment] 2015-11-10 11:11
We can create our own plugin. It's not a big deal

**Comment by LavrovArtem** [comment] 2015-12-14 13:51
duplicate of #331

**Comment by LavrovArtem** [comment] 2016-01-14 12:54
Also It needs to prohibit the using of the iterative functions of the array, in which the callback functions transferred, because it is slower than inline code and can be replaced by any framework.
List of the functions: ```filter```, ```forEach```, ```every```, ```map```, ```some```, ```reduce```, ```reduceRight```.

**Closed** 2016-01-15 12:06 UTC
Labels: AREA: client, COMPLEXITY: easy, TYPE: code style/structure issue
