### ISSUE TITLE
A test page hangs after login

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe-hammerhead#2349] opened 2020-06-16 09:23 UTC
https://github.com/DevExpress/testcafe-studio/issues/3189

Please see the test file from this SC ticket: https://supportcenter.devexpress.com/internal/ticket/details/T899457

Steps to reproduce:

1. Run `https-playground`
2. Open the page using the url defined in the test
3. Try to log in
4. The page will hang

I've reproduced this issue with `v1.7.3`, but it works as expected with version `1.6.3`.

**Comment by LavrovArtem** [comment] 2020-06-23 13:03
Duplicate of #2344

**Closed by LavrovArtem** 2020-06-23 13:03 UTC
Labels: REASON: duplicate, REGRESSION, TYPE: bug, support center
