### ISSUE TITLE
Support the spread syntax for object literals (new in ECMAScript 2018)

### ISSUE THREAD

**Issue by othree** [DevExpress/testcafe-hammerhead#1935] opened 2019-02-13 10:02 UTC
Hi

I have a private project using testcafe to do test.
And a strange behavior occurs but I am not able to create a simple sample to reproduce it.
So I am here to asking for some advice.

The issue is:

I have an iframe append to the body after the document is ready.
And I will postMessage to it with some user action.
But inside the iframe's message event, the value of `event.data` is undefined.

I did some investigation. And found there is a MessageSandbox.
Outside the iframe, the message data didn't wrapped by it.
But inside the iframe, the message is extracted by it, so the value becomes `undefined`.
I use breakpoint and a working case to do A/B test to identify this.

I try to build a simple sample try to reproduce this issue.
But I failed, do you have any idea is there any chance this issue could happen.

**Comment by LavrovArtem** [comment] 2019-02-13 14:45
Thank you for providing this information. However, it is not sufficient to find the cause of the issue and provide a solution. There can be different causes and without having access to your page or code, I cannot give you any advice.

**Comment by nico29** [comment] 2019-02-20 10:24
Hello,

We are facing a similar issue. We are using testcafe to run tests on our website built using [NextJS](http://nextjs.org), version 8.0.2 (and React version 16.8.2).
Recently our tests would not run and we received the following stacktrace.

```
 1) - Error in fixture.beforeEach hook -
      A JavaScript error occurred on "https://dev.gymlib.com/AXDefoasg/https://dev.gymlib.com/".
      At this moment, TestCafe tracks uncaught JavaScript errors on the page. Try to manually perform the test
      scenario.
      If this error still occurs then it means you site has uncaught JavaScript errors. To disable JavaScript error
      tracking you can turn the --skip-js-errors option on.
      If the error occurs only with TestCafe then it is a bug. Write a new issue about it at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      SyntaxError: Unexpected token )
          at exports.parse (http://192.168.1.21:56369/hammerhead.js:4:16155)
          at Function.t._getMessageData (http://192.168.1.21:56369/hammerhead.js:7:2165)
          at t._onMessage (http://192.168.1.21:56369/hammerhead.js:7:2215)
          at n (http://192.168.1.21:56369/hammerhead.js:13:27178)
          at n (http://192.168.1.21:56369/hammerhead.js:7:3525)
          at http://192.168.1.21:56369/hammerhead.js:6:27272
```
During our investigation, we found that the `parse` function of [json-hammerhead](https://github.com/miherlosev/json-hammerhead) was failing because it was invoked with an empty string.
The code invoking the parse function is located in the `MessageSandbox._getMessageData` and is called by the `MessageSandbox._onMessage` method, which received a `MessageEvent` with `data = ""`.

We looked for the code dispatching a message event w/ empty data, and it presumably is located in a webpack bundle emitted by NextJS using the [setimmediate](https://github.com/YuzuJS) package.
The code emitting the message event is [on line 93](https://github.com/YuzuJS/setImmediate/blob/master/setImmediate.js#L93).

Still, emitting empty data is allowed by the `postMessage` API. We think the main issue is that the `MessageSandbox._getMessageData` should perform a `try/catch` when parsing data ([code here](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/event/message.ts#L60)) and deal w/ errors (eventually return an empty object for later checks) since `JSON.parse` can throw.

We tried this by patching our local hammerhead.js and it works as expected (no more error).
Thank you.

**Comment by othree** [comment] 2019-02-21 02:29
I already create a reproducible sample.
Need some time to organize it well.
Here are the causes of this issue:

1. A Gatsby website
2. Use JS to dynamic create iframe
3. The JS file's extension is `mjs`
4. The code has spread operator `...` (object spread properties)

I always use gatsby build/serve. Not develop mode to find the issue.
And when I open the site with testcafe. I foudn the JS code are not modified by hammerhead.
Which mease, there is no `/*hammerhead|script|start*/` section.

**Comment by othree** [comment] 2019-02-21 09:03
Just created the sample project https://github.com/othree/hammerhead-spread-issue

**Comment by LavrovArtem** [comment] 2019-02-26 10:51
Thank you for the sample project. It helped me find out that, currently, we don't support the spread syntax for object literals (new in ECMAScript 2018). I think we will support this in the near future.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by LavrovArtem** [comment] 2019-03-13 13:23
This issue has already been fixed in this [PR](https://github.com/DevExpress/testcafe-hammerhead/pull/1956).
The fix will be published in the next release.

**Closed by LavrovArtem** 2019-03-13 13:23 UTC
Labels: SYSTEM: resource processing, TYPE: bug
