### ISSUE TITLE
The modal form is not loaded trying to load external PDF and display it inside canvas

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe-hammerhead#2342] opened 2020-06-09 13:13 UTC
Please take a look at
https://supportcenter.devexpress.com/internal/ticket/details/T877322

The test and detailed information is in related SC ticket

**Comment by LavrovArtem** [comment] 2020-06-23 14:09
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1221

**Closed by LavrovArtem** 2020-06-23 14:09 UTC
Labels: STATE: Need research, support center
