### ISSUE TITLE
Future support for HTTP/2?

### ISSUE THREAD

**Issue by adriancable** [DevExpress/testcafe-hammerhead#2432] opened 2020-09-06 19:49 UTC
Background: HTTP/2 is now 5 years old and supported by all mainstream browsers. Most web servers now not only support, but prefer, HTTP/2. Many web services work best with HTTP/2, and some will only work with HTTP/2. At some point TestCafe will probably need to support HTTP/2 to continue to be useful.

There are libraries like https://github.com/szmarczak/http2-wrapper which implement HTTP/2 (including ALPN negotiation) over an API that is compatible with the NodeJS http/https modules, which should make it possible to support HTTP/2 in testcafe-hammerhead without rewriting a lot of the proxy code.

Do you have any intentions or timelines in mind to support HTTP/2 in the future?

**Comment by miherlosev** [comment] 2020-09-07 07:45
Hi @adriancable
 
Thank you for your inquiry. We agree that http/2 support is very important and we will consider providing it. At present, we are focused on the features listed in our [roadmap](https://devexpress.github.io/testcafe/roadmap/)

As a workaround, you can add a [fallback](https://github.com/DevExpress/testcafe-hammerhead/issues/1960#issuecomment-471541700) to the http/1 protocol version for existing sites. 

This issue is a duplicate of [https://github.com/DevExpress/testcafe-hammerhead/issues/1960](https://github.com/DevExpress/testcafe-hammerhead/issues/1960). Track #1960 to be informed about our progress.


This isssue is a duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1960. Track the #1960 issue to be informed about our progress.

**Closed by miherlosev** 2020-09-07 07:45 UTC
Labels: STATE: Need response
