### ISSUE TITLE
Chrome crashes with STATUS_ACCESS_VIOLATION error message

### ISSUE THREAD

**Issue by arubtsov** [DevExpress/testcafe-hammerhead#2347] opened 2020-06-11 14:20 UTC
After setting cookies in `Request Hook`.
Original issue: https://supportcenter.devexpress.com/internal/ticket/details/T898409

**Comment by LavrovArtem** [comment] 2020-07-08 09:02
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1237

**Closed by LavrovArtem** 2020-07-08 09:02 UTC
Labels: STATE: Need research, TYPE: bug, support center
