### ISSUE TITLE
Focusing element inside shadow dom not working

### ISSUE THREAD

**Issue by rajaguruduraisamy-okta** [DevExpress/testcafe-hammerhead#2312] opened 2020-05-01 13:17 UTC
### What is your Scenario?
Application code calls focus() method on an element inside shadow dom. Test code tries to verify the element inside shadow dom is in focus.
 
### What is the Current behavior?
Native focus method is not called when the focus method is called from application for an element inside shadow dom. Testcafe considers the element is not visible and doesn't trigger the native focus method.
Probably because https://github.com/DevExpress/testcafe-hammerhead/blob/f68857f899c538b3ee054be75a1166fe5b1dcf1e/src/client/sandbox/event/focus-blur.ts#L273 think the element is invisible

https://github.com/DevExpress/testcafe-hammerhead/blob/4789241f9f93d43923fd892a74b4d4786b5e79d2/src/client/utils/style.ts#L329
 
### What is the Expected behavior?
Native focus method should be triggered if the element is inside shadow dom.
 
### What is your public web site URL?

```
const button = document.querySelector('custom-element').shadowRoot.querySelector('.close--button');
button.focus();
```

Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 await t.expect(Selector(() => {
    // @ts-ignore
    let activeElement = document.activeElement || document.body;
    
    while(activeElement && activeElement.shadowRoot) {
      const currentElement = activeElement.shadowRoot.activeElement;

      if (!currentElement) {
        break;
      }
      activeElement = currentElement;
    }
    return activeElement;
  }).hasClass('close--button')).ok();
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to: ...
2. Execute this command: ...
3. See the error: ...
 
### Your Environment details:

* node.js version:                    12.13.0
* browser name and version: Chrome 80
* platform and version:          macOS 10.14.6
* other:

**Comment by rajaguruduraisamy-okta** [comment] 2020-05-01 13:19
Filed an issue in [testcafe](https://github.com/DevExpress/testcafe/issues/4987) repo but not sure do we need to create one here.

**Comment by Farfurix** [comment] 2020-05-04 14:10
@rajaguruduraisamy-okta

Hello,

Is it a duplicate of the https://github.com/DevExpress/testcafe/issues/4987 issue?

**Comment by rajaguruduraisamy-okta** [comment] 2020-05-04 14:12
@Farfurix Yes !! Not sure whether this issue needs to be filed directly in testcafe-hammerhead repo or in testcafe repo

**Comment by Farfurix** [comment] 2020-05-04 14:25
@rajaguruduraisamy-okta 

No need to do it, I'll close it as a duplicate. If necessary, we'll [transfer](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) your original issue here.

**Closed by Farfurix** 2020-05-04 14:25 UTC
Labels: STATE: Need response
