### ISSUE TITLE
Page is not loaded

### ISSUE THREAD

**Issue by arubtsov** [DevExpress/testcafe-hammerhead#2073] opened 2019-07-15 09:12 UTC
### What is your Scenario?
Opening a page in `gulp http-playground`.
 
### What is the Current behavior?
There is a Blank page in a browser. I get `TypeError: Cross-origin script load denied by Cross-Origin Resource Sharing policy.` in Safari and `TypeError: Failed to fetch dynamically imported` in Chrome on Mac OS Mojave.
 
### What is the Expected behavior?
Able to interact with the page.
 
### What is your public web site URL?
The page from [T756324](https://isc.devexpress.com/Thread/WorkplaceDetails/T756324).

Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to: ...
2. Execute this command: ...
3. See the error: ...
 
### Your Environment details:

node.js version:                    10.16.0
Windows 10:
    works only in: IE 11 and Edge (fails in Chrome and Firefox)
Mac OS Mojave:
    fails in Chrome and Safari

**Comment by LavrovArtem** [comment] 2019-07-19 11:52
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1725.
This site uses the native imports.

**Closed** 2019-07-23 09:16 UTC
Labels: !IMPORTANT!, TYPE: bug, support center
