### ISSUE TITLE
Why does hammerhead respond with HTTP status 222 and not 500 when there is a CORS issue?

### ISSUE THREAD

**Issue by glennflanagan** [DevExpress/testcafe-hammerhead#2488] opened 2020-11-25 09:31 UTC
Hi there, apologies if this is not the right place to ask the question but it kind of feels like a bug in the design to me - but I'm looking for some understanding for the reason to use 222 as the HTTP status code when there is a CORS issue?

The reason I ask is because I ran into this issue while running testcafe tests on an application where running the test manually the test would pass, but running through testcafe it would fail but debugging the test there was nothing obviously wrong with the network requests. The 222 https status suggests that the network request is a successful one (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) and so our application was trying to continues as though everything was ok (when in fact the network request had failed).

Wouldn't an HTTP status code of 500 or something in the 500 range be more appropriate to highlight the CORS issue?

**Comment by arubtsov** [comment] 2020-11-26 08:48
Hello @glennflanagan,

Thank you for pointing this out. You are right, it might be a better solution to use one of the 5xx status codes in that case. Our team will consider changing this behavior in one of the future releases.

**Comment by LavrovArtem** [comment] 2020-11-30 13:50
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1263

**Closed by LavrovArtem** 2020-11-30 13:50 UTC
Labels: TYPE: enhancement
