### ISSUE TITLE
when running in angular 14 we get SyntaxError: cannot use `??` unparenthesized within `||` and `&&` expressions

### ISSUE THREAD

**Issue by jlabaj** [DevExpress/testcafe-hammerhead#2781] opened 2022-07-01 13:10 UTC
### What is your Scenario?

when running in angular 14 we get SyntaxError: cannot use `??` unparenthesized within `||` and `&&` expressions

### What is the Current behavior?

all test fail because of this error in hammerhead

### What is the Expected behavior?

no error

### What is your public website URL? (or attach your complete example)

cant share

### What is your TestCafe test code?

fixture `board tests`
	.page(E2eConstants.URL)
    .beforeEach(async (t) => {
		await t
			.maximizeWindow() --> fails here
			.useRole(roles.testUser)
		await NavigationBL.navigateFromLoginToOverview();
    })

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.19.0

### Node.js version

16.15.1

### Command-line arguments

set TESTCAFE_ENV=https://localhost:4200/ && testcafe chrome ./e2e/src/tests

### Browser name(s) and version(s)

102.0 (64-bit), chrome 103.0.5060.66 (Official Build) (64-bit)

**Comment by Aleksey28** [comment] 2022-07-04 07:56
Duplicate of https://github.com/DevExpress/angular-testcafe/issues/86

**Closed by Aleksey28** 2022-07-04 07:56 UTC
Labels: TYPE: bug, STATE: Need response
