### ISSUE TITLE
Support javascript files with type=module

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1725] opened 2018-08-15 09:20 UTC
Roadmap:
- [x] es6-module
- [ ] import/export

https://jakearchibald.com/2017/es-modules-in-browsers/

**Comment by miherlosev** [comment] 2018-09-14 10:56
https://github.com/DevExpress/testcafe-hammerhead/issues/1373

**Comment by marchugon** [comment] 2018-11-30 13:44
Hi, 

+1 on this issue, having problems on our side also

**Comment by theTainted** [comment] 2019-02-11 13:57
Hi,
was this issue fixed in the latest version. or are we expecting a fix ?

**Comment by vladyslav2** [comment] 2019-02-19 18:25
any timeline when that problem gonna be fix?
Or maybe any rough ideas?

**Comment by LavrovArtem** [comment] 2019-02-20 16:00
Any personal estimate may be misleading, so I cannot tell you the precise date. Currently, I'm working on the `es6-module` support without the `import/export` keyword support.

**Comment by vladyslav2** [comment] 2019-02-20 19:23
@LavrovArtem thanks!
We are highly depended on that feature, so if you would need help with a testing or if you will have some pre-alpha release please let us know

**Comment by LavrovArtem** [comment] 2019-02-21 15:14
Thank you for your interest. The `es6-module` support (without `import/export`) has already been merged. I cannot currently tell you when we will publish TestCafe with this fix. Maybe, we will do it next week.

**Comment by theTainted** [comment] 2019-02-21 15:22
@LavrovArtem   Thanks for this, This issue was a deal breaker for me. Great to see that it is been looked into and fixed.

**Comment by aleks-pro** [comment] 2019-07-23 09:15
https://github.com/DevExpress/testcafe-hammerhead/issues/2073

**Comment by vogloblinsky** [comment] 2019-08-08 02:17
Any news on that issue @miherlosev ?
Need help ?

**Comment by rodrigotolledo** [comment] 2019-08-08 05:30
We're also being impacted by this issue.

Here is an example of what our code looks like:


`<script type="module"
       src="<%= htmlWebpackPlugin.options.cdnUrl %>/abc-app@dev/dist/abc-app/abc-app.esm.js"
       data-fl-resources-url="<%= htmlWebpackPlugin.options.cdnUrl %>/abc-app@dev/dist/abc-app"
       data-fl-namespace="abc-app">
   </script>`


We're using `TestCafe 1.3.3` and when test navigates to the page, we see the following error:


`TypeError: Failed to fetch dynamically imported module: http://10.10.8.18:45280/abc-app.entry.js`


`ERROR Error: Uncaught (in promise): Error: Constructor for "abc-app#undefined" was not found
Error: Constructor for "abc-app#undefined" was not found
   at initializeComponent (chunk-9c3af8d4.js:1769)
   at resolvePromise (hr-app-es2015.js:134537)
   at hr-app-es2015.js:134447
   at hr-app-es2015.js:134463
   at ZoneDelegate.invoke (hr-app-es2015.js:134099)
   at Object.onInvoke (hr-app-es2015.js:71053)
   at ZoneDelegate.invoke (hr-app-es2015.js:134098)
   at Zone.run (hr-app-es2015.js:133864)
   at hr-app-es2015.js:134595
   at ZoneDelegate.invokeTask (hr-app-es2015.js:134131)
   at Object.onInvokeTask (hr-app-es2015.js:71034)`

![testcafe-error](https://user-images.githubusercontent.com/1910338/62677317-3d681900-b9f1-11e9-9275-c8d081e6fbbd.png)


Is there any workaround that we can use for now? (so we can at least automate this page)

Thank you!

**Comment by miherlosev** [comment] 2019-08-08 08:39
@vogloblinsky 

The `<script type="module">` directive is already supported (`testcafe@1.4.0`)
Support of the dynamic imports is on the way.

@rodrigotolledo
Please wait until we implement this feature completely. If the problem persists after that, we will inspect it more deeply.

**Comment by vogloblinsky** [comment] 2019-08-09 22:20
@miherlosev Just created a repro repository : https://github.com/vogloblinsky/testcafe-stencil
It just a simple html page loading a Stencil Web Component.
The page runs perfectly alone, but none inside testcafe/hammerhead.

![Capture d’écran 2019-08-10 à 00 16 30](https://user-images.githubusercontent.com/2841805/62812080-91175700-bb04-11e9-968c-6387465bef53.png)
![Capture d’écran 2019-08-10 à 00 16 41](https://user-images.githubusercontent.com/2841805/62812084-95437480-bb04-11e9-8681-5abbadad4908.png)

**Comment by helen-dikareva** [comment] 2019-08-12 12:29
@vogloblinsky I was able to reproduce the problem you described. 
It seems like the problem is related to using the `import/export` functionality in your module. Currently, this feature isn't officially supported. 
Please wait until we finish our work on the implementation of this functionality. If the problem persists, we will fix it in a separate issue.

**Closed** 2019-08-26 14:45 UTC
Labels: TYPE: bug, support center

**Comment by vogloblinsky** [comment] 2019-08-27 12:29
@miherlosev Problem still persist with testcafe-hammerhead 1.9.0 in my repo repository.

**Comment by miherlosev** [comment] 2019-08-27 14:41
@vogloblinsky 

We've investigated your example and decided to create a separate issue for you case - https://github.com/DevExpress/testcafe-hammerhead/issues/2122. Track it be informed about our progress.

**Comment by vogloblinsky** [comment] 2019-08-27 15:21
Thanks
