### ISSUE TITLE
Testcafe runs into JS error at start of tests and crashes Safari 15 

### ISSUE THREAD

**Issue by aquaductape** [DevExpress/testcafe-hammerhead#2695] opened 2021-09-24 10:09 UTC
### What is your Scenario?

Run tests
 
### What is the Current behavior?

Safari 15 throws JS error at start of test and crashes, I provided the log below. Using skipJsErrors to true, didn't make a difference.
 
<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```html
 <!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <button id="first-button">first button</button>
  <button id="last-button">last button</button>
</body>

</html>
```

```js
fixture`Basic Dropdown`.page`../foo.html`;


test("test", async (t) => {
  await t.click("#last-button")
})
```
</details>

<details>
<summary>Error Logs:</summary>

```
> testcafe

 Running tests in:
 - Safari 15.0 / macOS 10.15.7

 Basic Dropdown
 ✖ test

   1) A JavaScript error occurred on "file:///Users/glentaylor/Documents/solid-dismiss/test/foo.html".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors" configuration file property to
      "true".
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      undefined is not an object (evaluating 'nativeMethods.objectHasOwnProperty.call(descriptor, 'writable')')
      hasOwnProperty@[native code]
      createOverriddenDescriptor@http://glens-macbook-air.local:64027/hammerhead.js:389:53
      overrideDescriptor@http://glens-macbook-air.local:64027/hammerhead.js:401:49
      @http://glens-macbook-air.local:64027/hammerhead.js:24802:28
      @http://glens-macbook-air.local:64027/hammerhead.js:24819:49
      @http://glens-macbook-air.local:64027/hammerhead.js:24883:59
      @http://glens-macbook-air.local:64027/testcafe-ui.js:906:21
      @http://glens-macbook-air.local:64027/testcafe-ui.js:952:51
      @http://glens-macbook-air.local:64027/testcafe-ui.js:974:36
      @http://glens-macbook-air.local:64027/testcafe-ui.js:987:29
      @http://glens-macbook-air.local:64027/testcafe-ui.js:989:102

      Browser: Safari 15.0 / macOS 10.15.7

          4 |
          5 |const id = "#basic";
          6 |const idClass = ".basic";
          7 |
          8 |test("test", async (t) => {
       >  9 |  await t.click("#last-button")
         10 |})
         11 |
         12 |// test("open on click menuButton", async (t) => {
         13 |//   await t.click(`${idClass}-1-container button`);
         14 |//   await t.expect(exists(`${id}-1-popup`)).ok();

         at <anonymous> (/Users/glentaylor/Documents/solid-dismiss/test/tests/basic-dropdown.ts:9:11)
         at <anonymous> (/Users/glentaylor/Documents/solid-dismiss/test/tests/basic-dropdown.ts:8:71)
         at __awaiter (/Users/glentaylor/Documents/solid-dismiss/test/tests/basic-dropdown.ts:4:12)
         at <anonymous> (/Users/glentaylor/Documents/solid-dismiss/test/tests/basic-dropdown.ts:8:26)



 1/1 failed (0s)
 ELIFECYCLE  Test failed. See above for more details.
```
</details>
 
### Your Environment details:

* node.js version:                    v16.10.0
* browser name and version: Safari 15.0
* platform and version:          macOS 10.15.7

**Comment by mm-brn** [comment] 2021-09-24 12:06
Same issue here. Safari 15 on Big Sur 11.6

Here is a Screenshot of the minified code throwing the exception: 
![image](https://user-images.githubusercontent.com/81223299/134671385-4d24caf0-98b7-4a46-b51e-3f37bfd77790.png)

Seems to be related to CSSStyleDeclaration

**Comment by Farfurix** [comment] 2021-09-27 08:21
Hello,

This issue is a duplicate of [https://github.com/DevExpress/testcafe/issues/6546](https://github.com/DevExpress/testcafe/issues/6546) so I'll close it. Please track the mentioned issue for updates.

**Closed by Farfurix** 2021-09-27 08:21 UTC
Labels: STATE: Need response
