### ISSUE TITLE
Error on eligrey.com/demos/FileSaver.js/

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#1346] opened 2017-10-24 12:22 UTC
Hammerhead playground can't load https://eligrey.com/demos/FileSaver.js/.

Expected:
![image](https://user-images.githubusercontent.com/4479386/31942666-bbebb19a-b8ce-11e7-83b1-935599f4bcb9.png)

No errors in the console without hammerhead.

Got:
![image](https://user-images.githubusercontent.com/4479386/31942688-d583a478-b8ce-11e7-9851-e6669fa7cb25.png)

Console:
![image](https://user-images.githubusercontent.com/4479386/31942701-ddef5abc-b8ce-11e7-9db1-78cbce86a924.png)

**Comment by miherlosev** [comment] 2017-12-18 14:09
Problem is in encoding/decoding.
![Markup](https://user-images.githubusercontent.com/4133518/34109924-2da31f36-e416-11e7-8320-f7ebf4a4675a.png)

**Comment by LavrovArtem** [comment] 2020-03-05 08:43
duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/350

**Closed by LavrovArtem** 2020-03-05 08:43 UTC
Labels: REASON: duplicate
