### ISSUE TITLE
Incorect handling of HTML Imports when WebComponents polyfill is used

### ISSUE THREAD

**Issue by sorin-davidoi** [DevExpress/testcafe-hammerhead#1668] opened 2018-07-03 10:41 UTC
The [HTML Imports polyfill](https://github.com/webcomponents/html-imports) works by [sending XHR requests](https://github.com/webcomponents/html-imports/blob/master/src/html-imports.js#L167). This currently breaks websites when run inside TestCafe since no processing is done to the response.

A workaround would be to process responses as HTML pages if the response's `Content-Type` is set to `text/html` (even if the request was made with XHR).

**Comment by LavrovArtem** [comment] 2018-07-05 13:59
Hi @sorin-davidoi,
I've investigeted this issue on the [webcomponents.org](https://www.webcomponents.org/polyfills/) which is used the HTML Import polyfill and did not find problem with XHR requests. But I found [another issue](https://github.com/DevExpress/testcafe-hammerhead/issues/1673).

**Comment by sorin-davidoi** [comment] 2018-07-13 14:15
I'm attaching a small demo that reproduces the problem. However, I was wrong about the cause of the issue - it is not due to the way the server processes responses. Instead, it appears to be cause by the way some client-side API are reimplemented (e.g. accessing `href` from a link inside a document which has a `base`?).

If you load `index.html` in Firefox is will show an alert dialog. If you load it from `testcafe-hammerhead` (via the `http-playground`) the alert dialog is not shown (you can see one request failing do the the fact that the path is wrong).

[demo.zip](https://github.com/DevExpress/testcafe-hammerhead/files/2192979/demo.zip)

**Comment by sorin-davidoi** [comment] 2018-07-13 14:21
Now that I take a closer look at #1673 it looks like it is the same issue. Feel free to close this if that is the case.

**Comment by LavrovArtem** [comment] 2018-07-16 08:49
Hi @sorin-davidoi,
Yes I think that it is duplicate of the  https://github.com/DevExpress/testcafe-hammerhead/issues/1673 issue. I'll close this issue but feel free to reopen it if the problem will be reproduced again after the #1673 fix.

**Closed by LavrovArtem** 2018-07-16 08:49 UTC
Labels: Need to reproduce
