### ISSUE TITLE
Unload proxy for local addresses

### ISSUE THREAD

**Issue by ggrimbert** [DevExpress/testcafe-hammerhead#1339] opened 2017-10-09 08:37 UTC
Hi,

I don't know if this is a bug, a feature request or a config problem of mine...

When I launch my test page, file loading are slow. A file that normally takes 500ms takes 6.5s; I found that this is the proxying of the urls you set. The file is 1.5MB, on dev / prod it's pretty fast.

This url takes 6.5s
```
http://192.168.0.110:34580/rJwhE2u3Z!s!utf-8/http://localhost:1337/node_modules/konnect-web-core/scripts/kendo-dependencies.js
```

This url takes 5..ms
```
http://localhost:1337/node_modules/konnect-web-core/scripts/kendo-dependencies.js
```

Is there a way to not proxying localhost urls ?
I've tried to modify your code by adding an if, the url is now OK, but the page reloads infinitely.

I launch testcafe with the following params : 
```
testcafe --skip-js-errors -s /home/kimoce/Téléchargements/toto/screen/ 'chrome --user-data-dir=/tmp/temp-chrome-profile --no-proxy-server --auto-open-devtools-for-tabs' test.js
```

I'm running on Linux (Ubuntu 16.04) with the last stable version of Chrome available. I've tried too on fedora 19 wit chrome 47.

**Comment by miherlosev** [comment] 2017-10-09 10:54
Hi, ggrimbert
> Is there a way to not proxying localhost urls ?

There is no such a way.

> A file that normally takes 500ms takes 6.5s;

It looks like a bug. 
I can't find a module called `konnect-web-core` in npm.
Could you please share code of the `konnect-web-core` module?

**Comment by ggrimbert** [comment] 2017-10-09 12:14
This code is from my company. But I found a way to reproduce the error with an online page.

```javascript
import { Selector } from 'testcafe';

fixture `test`.page(`http://demos.telerik.com/kendo-ui/grid/index`);

test('openpage', async testSelector => {
    await testSelector.wait(50000);
});
```

Launch tests with dev tools open and check the the time required to get the script files.

This is the result when directly calling the url in chrome : 
![image](https://user-images.githubusercontent.com/15869188/31337474-d0451cfa-acfb-11e7-8ae9-d0b754cc2810.png)


This is the result when calling the url from testcafe : 
![image](https://user-images.githubusercontent.com/15869188/31337518-fa43a5a8-acfb-11e7-9aa7-eaabdaadde3b.png)

Just check the time needed for loading kendo.all.min.js

The url I gave in the test case is from KendoUI, we use it in our app.

**Comment by miherlosev** [comment] 2017-10-09 13:02
@ggrimbert 
I've reproduced your issue. It relates to proxying resources from CDNs.
It will be fixed after we implement HTTP caching on our side (https://github.com/DevExpress/testcafe-hammerhead/issues/863)

**Closed by miherlosev** 2017-10-09 13:02 UTC
Labels: TYPE: question

**Comment by ggrimbert** [comment] 2017-10-09 13:07
What can I do before cache is done ? 

Loading is too slow to be usable.

**Comment by miherlosev** [comment] 2017-10-09 13:47
> What can I do before cache is done ?

As I understand from this [issue](https://github.com/DevExpress/testcafe/issues/1844), you use a proxy. 
You can cache javascript libraries in your proxy to reduce round trips to CDN.


> Loading is too slow to be usable.

I've measured an average time of `DOMContentLoaded` and `load` events per 5 page opens:
without `testcafe`: `DOMContentLoaded` - 1.5 sec, `load` - 2.5 sec.
with `testcafe`: `DOMContentLoaded` - 3 sec, `load` - 5.5 sec.
