### ISSUE TITLE
LocalStorage raises QuotaExceededError while using `castToString` in StorageWrapper

### ISSUE THREAD

**Issue by anubhavsagar** [DevExpress/testcafe-hammerhead#1454] opened 2018-01-23 14:33 UTC
Within **StorageWrapper** (src/client/sandbox/storages/wrapper.js), the method castToString (line 160) is used to convert value to string. This uses the localStorage itself for the conversion. This fails with a QuotaExceededError if the localStorage already holds a lot of data.

As a result the amount of data that could be pushed into LocalStorage by the app reduces to half the browser's actual localStorage limit.

Moreover, we do not handle the error at this point, leading to a test case failure.

As a result, even when I am not hitting the theoretical limits of localStorage, the testcases fail for me with the QuotaExceededError

**Comment by miherlosev** [comment] 2018-01-24 08:46
Hi @anubhavsagar.
Thanks for your bug report. 
Until the bug is fixed, you can try a temporary workaround.
In your fork, replace `castToString(...)` with `String(...)` in two places: https://github.com/DevExpress/testcafe-hammerhead/blob/3aacda98c9a589fe50871823e6d683ac25b9b6b1/src/client/sandbox/storages/wrapper.js#L182 https://github.com/DevExpress/testcafe-hammerhead/blob/3aacda98c9a589fe50871823e6d683ac25b9b6b1/src/client/sandbox/storages/wrapper.js#L229. 
Then build your own version of `hammerhead.js` and put it to `node_modules/testcafe-hammerhead/lib/client`. 
Let me know about your result.

**Comment by magnanimus1994** [comment] 2020-03-17 12:24
Is there a fix planned @LavrovArtem ?  My team is seeing this issue as well.

**Comment by Dmitry-Ostashev** [comment] 2020-03-18 16:10
This issue is in our plans, but we cannot provide any estimates at this time.

**Comment by adewinter** [comment] 2020-04-13 15:19
@LavrovArtem / @Dmitry-Ostashev , if we create a PR with the fix as laid out by @miherlosev (above) would you be willing to merge it in?

**Comment by miherlosev** [comment] 2020-04-14 08:06
Hi @adewinter 

Thank you for your desire to fix this issue. We've added this issue to the [current development sprint](https://github.com/DevExpress/testcafe-hammerhead/milestone/60). @LavrovArtem is working on it right now.

**Comment by Farfurix** [comment] 2020-04-20 11:14
I'm working on it.

**Comment by Farfurix** [comment] 2020-04-29 07:42
At present, the TODO list for the issue is:
- [x] https://github.com/DevExpress/testcafe-hammerhead/pull/2302
- [ ] **Find a solution to compress storage without using third-party packages on our client side**.

**Comment by Farfurix** [comment] 2020-05-20 09:43
I will close this issue since the original `castToString` issue [was fixed](https://github.com/DevExpress/testcafe-hammerhead/pull/2302). Also, I opened a new issue related to storages compression. You can track our progress here: https://github.com/DevExpress/testcafe-hammerhead/issues/2325.

**Closed by Farfurix** 2020-05-20 09:43 UTC
Labels: AREA: client, FREQUENCY: level 2, SYSTEM: storages, TYPE: bug
