### ISSUE TITLE
Testcafe hammerhead processing transforms break JavaScript

### ISSUE THREAD

**Issue by alex-zh** [DevExpress/testcafe-hammerhead#2746] opened 2022-02-21 17:50 UTC
### What is your Scenario?

JavaScript bundle is generated by webpack+babel and has code like the following:
o=(t&&t["function.value"])??null
hammerhead processing transforms  it into
o=t&&t["function.value"]??null
that leads to errors like 
Uncaught SyntaxError: Unexpected token '??'

While running tests in browser log we get mysterious errors  like the following:

![image](https://user-images.githubusercontent.com/6177523/155004809-72d846f2-ccfe-4968-a717-edbb196d479b.png)

Tested on "testcafe": "1.18.4"

My questions
1. how can we workaround this problem?
2. can we disable unwanted transformation?

Alexander

### What is the Current behavior?

JavaScript bundle is generated by webpack+babel and has code like the following:
o=(t&&t["function.value"])??null
hammerhead processing transforms  it into
o=t&&t["function.value"]??null

### What is the Expected behavior?

o=(t&&t["function.value"])??null
should be transformed into 
o=(t&&t["function.value"])??null 
or should not be transformed at all

### What is your public website URL? (or attach your complete example)

o=(t&&t["function.value"])??null

### What is your TestCafe test code?

o=(t&&t["function.value"])??null

### Screenshots

![image](https://user-images.githubusercontent.com/6177523/155005434-129179a5-034a-49a1-93c2-86cbe4f5cb0f.png)

### Steps to Reproduce

1. -

### TestCafe version

1.18.4

### Command-line arguments

none

**Comment by miherlosev** [comment] 2022-02-22 07:40
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/2714

**Closed by miherlosev** 2022-02-22 07:40 UTC
Labels: TYPE: bug, STATE: Need response
