### ISSUE TITLE
Private class fields are undefined in public getters/setters

### ISSUE THREAD

**Issue by iggyfisk** [DevExpress/testcafe-hammerhead#2825] opened 2022-12-20 22:15 UTC
### What is your Scenario?

Our library has a class that uses private fields that are accessed through public getters/setters. When testing it in testcafe, the script crashes immediately even though it works fine when browsing normally.

### What is the Current behavior?

When running in testcafe, the private field is `undefined` when accessed inside a class instances' getter/setter.

### What is the Expected behavior?

The private field should contain the correct value set earlier on the class instance.

### What is your public website URL? (or attach your complete example)

A simple reproduction repository is available on https://github.com/iggyfisk/hammerhead-getter-reproduction

### What is your TestCafe test code?

```TypeScript
import * as testcafe from "testcafe";

testcafe.fixture("Class instance getter").page(`http://127.0.0.1:1234/index.html`);

testcafe.test("Text should be the value", async tc => {
  await tc.expect(testcafe.Selector("div").innerText).eql("foo");
});
```

(Also available in the reproduction repository)

### Screenshots

![Screenshot 2022-12-20 at 23 12 29](https://user-images.githubusercontent.com/6059552/208776781-4cf14227-4ab9-41bb-ad62-37b36731b42f.png)

### Steps to Reproduce

1. Clone https://github.com/iggyfisk/hammerhead-getter-reproduction.git
2. Follow the instructions in `README.md`

### TestCafe version

2.1.0

### Command-line arguments

testcafe --debug-on-fail chrome test.ts

### Browser name(s) and version(s)

Chrome 108, Firefox 108

### Platform(s) and version(s)

macOS 13.1

**Comment by miherlosev** [comment] 2022-12-21 05:04
Duplicate of https://github.com/DevExpress/testcafe/issues/7238.

**Closed by miherlosev** 2022-12-21 05:04 UTC
Labels: TYPE: bug, STATE: Need response
