### ISSUE TITLE
The last input's value is not restored in window.history.back() was called

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#731] opened 2016-08-12 08:52 UTC
The steps to reproduce:

``` html
                   open a page with an input with value '111'
                   change input's value to '222'
                   go to any other page
                   call 'window.history.back' in console

          without hammerhead-playground      |       with hammerhead-playground
              input value is '222'           |           input value is '111'

```

Reproduced in Chrome and FF (Not reproduced in IE11. The value is "222" in both cases).

**Comment by LavrovArtem** [comment] 2020-02-17 08:28
duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1013

**Closed by LavrovArtem** 2020-02-17 08:28 UTC
Labels: AREA: client, BROWSER: Chrome, BROWSER: Firefox, SYSTEM: client side processing, TYPE: enhancement
