### ISSUE TITLE
Resource http://w.uptolike.com/widgets/v1/widgetsModule.js?v=a5312ff27600864378d92e743a16cd02 is not processed

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#591] opened 2016-05-18 11:25 UTC
see https://testcafe-hhhm.devexpress.com/history?timestamp=1463511795638&siteUrl=http://elementy.ru.

**Comment by miherlosev** [comment] 2016-05-19 08:38
I'm working on this

**Comment by miherlosev** [comment] 2016-05-19 12:00
This code is not processed:
```javascript
    function e() {
        console.log('executed');
    }
    /true/i.test('true') ? e() : window.postMessage('data', '*');
```
If I replace reqular expression on `true` string then all works right.

**Comment by churkin** [comment] 2016-05-24 15:34
`function a(){function b(){}/k/;}`

**Comment by inikulin** [comment] 2016-05-24 16:24
@churkin Acorn bug?

**Comment by inikulin** [comment] 2016-05-24 16:30
Works just fine with [Babylon](https://github.com/babel/babylon). Maybe it's make sense to swtich to it? Note that it uses flow types syntax, so it makes sense to add their `.babelrc` and missing plugins to our build.

**Comment by churkin** [comment] 2016-05-25 10:48
I could not reproduce the problem at the pure acorn v3.1.0. It looks like hammerhead acorn version does not match the real v3.1.0. @LavrovArtem

**Comment by LavrovArtem** [comment] 2016-05-26 08:37
I'm working on this

**Comment by LavrovArtem** [comment] 2016-05-26 12:05
I created issue on acorn https://github.com/ternjs/acorn/issues/416.

**Comment by LavrovArtem** [comment] 2016-05-26 12:05
I removed the http://elementy.ru site from Health Monitor, after fixing this issue it needs to return it back.

**Comment by inikulin** [comment] 2016-05-26 12:55
> I removed the http://elementy.ru site from Health Monitor, after fixing this issue it needs to return it back.

Why? We have an issue and it's not fixed. Why hide it?

**Comment by inikulin** [comment] 2016-05-26 13:00
Also, I still vote for switching to Babylon: e.g. acorn doesn't have support for `async` functions, but both Edge and IE landed support in their dev versions. So we will see them in the wild soon.

**Comment by inikulin** [comment] 2016-05-26 13:02
\cc @churkin @LavrovArtem

**Comment by LavrovArtem** [comment] 2016-05-26 13:15
Are there any speed tests acorn and babylon?

**Comment by inikulin** [comment] 2016-05-26 13:18
Babylon is basically a fork of acorn.

**Comment by churkin** [comment] 2016-05-26 14:06
@LavrovArtem let's try

**Closed** 2016-05-27 14:37 UTC
Labels: !IMPORTANT!, AREA: server, SYSTEM: resource processing, TYPE: bug
