### ISSUE TITLE
React error on a DevExtreme Demo Page 

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#2000] opened 2019-04-19 11:05 UTC
Open http://localhost:1401/sB8yF3fY7/https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/ in Playground. Result:
```js
hammerhead.js:10808 Invariant Violation: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:435
    at i (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:559)
    at Object.Bl [as createPortal] (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:102229)
    at t.value (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:87:7890)
    at t.value (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:87:8188)
    at Ra (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:63993)
    at ja (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:63788)
    at Ia (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:67622)
    at qi (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:91822)
    at $i (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:92206)
window.console.(anonymous function) @ hammerhead.js:10808
fi @ index.js?v=1553778960:78
Ci.n.callback @ index.js?v=1553778960:78
oi @ index.js?v=1553778960:78
ri @ index.js?v=1553778960:78
Hi @ index.js?v=1553778960:78
Bi @ index.js?v=1553778960:78
(anonymous) @ index.js?v=1553778960:78
t.unstable_runWithPriority @ index.js?v=1553778960:87
Nl @ index.js?v=1553778960:78
Rl @ index.js?v=1553778960:78
Tl @ index.js?v=1553778960:78
xl @ index.js?v=1553778960:78
Ji @ index.js?v=1553778960:78
Ml @ index.js?v=1553778960:78
Gl @ index.js?v=1553778960:78
Vl.render @ index.js?v=1553778960:78
(anonymous) @ index.js?v=1553778960:78
Il @ index.js?v=1553778960:78
Wl @ index.js?v=1553778960:78
render @ index.js?v=1553778960:78
(anonymous) @ index.js?v=1553778960:115
(anonymous) @ index.js?v=1553778960:115
n @ index.js?v=1553778960:2
(anonymous) @ index.js?v=1553778960:62
n @ index.js?v=1553778960:2
(anonymous) @ index.js?v=1553778960:2
(anonymous) @ index.js?v=1553778960:2
index.js?v=1553778960:78 Uncaught Invariant Violation: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:435
    at i (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:559)
    at Object.Bl [as createPortal] (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:102229)
    at t.value (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:87:7890)
    at t.value (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:87:8188)
    at Ra (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:63993)
    at ja (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:63788)
    at Ia (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:67622)
    at qi (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:91822)
    at $i (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:92206)
```

No errors without hammerhead

**Comment by churkin** [comment] 2019-04-19 11:24
Devextreme reactive team waiting for this, we can use testcafe now.

**Comment by LavrovArtem** [comment] 2019-04-23 07:44
The problem is related to our self-removing script that is added to the body. The link element blocks the parsing stream that stops when is faced with any script element. As a workaround, you can mark the link as [async](https://codepen.io/tigt/post/async-css-without-javascript).

Example for the reproducing:
```html
<iframe></iframe>
<script>
    var idoc = document.querySelector('iframe').contentDocument;

    idoc.open("text/html", "replace");
    idoc.write('<!DOCTYPE html><html><head><link rel="stylesheet" href="./style.css"></head>',
               '<body><div id="mountPoint"></div></body></html>');
    idoc.close();

    if (idoc.body.children[0].id !== 'mountPoint')
        alert('wrong');
</script>
```

**Comment by churkin** [comment] 2019-04-25 14:11
@LavrovArtem What about fix?

**Comment by AlexKamaev** [comment] 2019-04-26 09:31
@churkin 
We're working on this issue, however, it seems complex enough, so I can not give you a precise time frame as to when it will be fixed.

**Closed** 2019-05-17 08:56 UTC
Labels: !IMPORTANT!, AREA: client, SYSTEM: sandbox, TYPE: bug
