### ISSUE TITLE
undefined window property crashes application when native automation mode is activated 

### ISSUE THREAD

**Issue by Thomas-Haider** [DevExpress/testcafe-hammerhead#2942] opened 2023-08-03 09:25 UTC
### What is your Scenario?

We have a platform application, where we load apps in iframes of the main iframes. Sadly, when we enabled native automation mode, we have this situation where the window property in the [backup.ts](https://github.com/DevExpress/testcafe-hammerhead/blob/e7bc19fd181f73ccf615d3e79985b9187f2c7e8d/src/client/sandbox/backup.ts#L45C42-L45C42) file is undefined. 

### What is the Current behavior?

Following error gets thrown when the page gets loaded initially: 
![image](https://github.com/DevExpress/testcafe-hammerhead/assets/43231671/f001d57c-85f8-4ad2-a901-e7a9ea8b0c02)

### What is the Expected behavior?

I wouldn't expect any issues when opening our platform when native automation mode is enabled. 

### What is your public website URL? (or attach your complete example)

Can't share and sadly, i did not manage to reproduce this outside of our environement 

### What is your TestCafe test code?

Can't share details but it is just logging in into our SSO screen and then expecting true to equals false :D 

```typescript
fixture('dd').page('some url i can't share');

test('test', async (testController) => testController
    .typeText(SSoScreenPo.EMAIL, username)
    .click(SSoScreenPo.NEXT_BTN)
    .typeText(SSoScreenPo.PASSWORD, pw)
    .click(SSoScreenPo.SIGN_IN_BTN)
    .expect(true)
    .ok());
```

### Your complete configuration file

native automation mode is enabled by default

### Your complete test report

application throws error in react boundary and therfore the test fails as it obviously can't find the intended selectors

### Steps to Reproduce

Unable to reproduce the issue outside our environment

### TestCafe version

3.1.0

### Node.js version

16.18.1

### Command-line arguments

testcafe chrome test.tc-spec.ts --live

### Browser name(s) and version(s)

Chrome 115.0.0.0 / Ventura 13

### Platform(s) and version(s)

macOS

### Other

I manage to workaround this issue by checking if the passed down window property is undefined and if it is undefined I assigne the `window = this`. In this case `this` holds the window property.

My proposal for fixing the issue would be the following: 
https://github.com/DevExpress/testcafe-hammerhead/blob/e7bc19fd181f73ccf615d3e79985b9187f2c7e8d/src/client/sandbox/backup.ts#L45

add the following code at the beginning of the method:
```typescript
 if(!window)
      window = this;
```
so the function would look like this:

```typscript
function get(window) {
    if(!window)
        window = this;

    var topSameDomainWindow = getTopSameDomainWindow(window);
    var storage = topSameDomainWindow[SANDBOX_BACKUP];
    var iframe = window !== topSameDomainWindow ? window.frameElement : null;
    if (storage) {
	      var record = findRecord(storage, iframe);
	      return record ? record.sandbox : null;
    }
    return null;
}
```

With this changes i do not have any issues and therefore I would be greatful if you guys could introduce them :) ,

**Comment by Thomas-Haider** [comment] 2023-08-03 09:29
Further prove to my workaround: 
when I add a `debugger;` in the if that checks if the window property is undefined, i see the following following variable assigned:
![image](https://github.com/DevExpress/testcafe-hammerhead/assets/43231671/2cf92052-50b2-4ba7-9f67-58c76208c1d2)

**Comment by miherlosev** [comment] 2023-08-03 10:02
Duplicate of https://github.com/DevExpress/testcafe/issues/7886

**Closed by miherlosev** 2023-08-03 10:02 UTC
Labels: TYPE: bug, STATE: Need response

**Comment by Thomas-Haider** [comment] 2023-08-03 11:04
Thanks!
