### ISSUE TITLE
Actions can't be performed in iframe on fiddle.net

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#1921] opened 2019-02-06 16:17 UTC
### What is your Test Scenario?
I'm trying to record actions in a result iframe on fiddle.net after click on a `Run` button
https://github.com/DevExpress/testcafe-studio/issues/2052
 
### What is the Current behavior?
Error raises `TestCafeDriver doesn't exist in the iframe`
 
### What is the Expected behavior?
I expect TestCafeDriver exists in the iframe
 
### Steps to Reproduce:
The easiest way to reproduce is to run a following test:
```js
import { Selector } from 'testcafe';

fixture `f`
    .page `https://jsfiddle.net/`;

test('t', async t => {
    await t
        .debug() //resume after loading is complete
        .click(Selector('#run'))
        .debug() // resume after result iframe has a white background
        .switchToIframe(Selector('[name="result"]'))
        .click(Selector('body')); // error raises 'Content of the iframe in which the test is currently operating did not load.'
});
```

On the second `debug` action you can check that TestCafeDriver instance doesn't exist in iframe
![image](https://user-images.githubusercontent.com/12034551/52355445-63f9c700-2a43-11e9-8a5f-cad9a0c30310.png)

 
### Your Environment details:
* testcafe version:                  0.23.3

**Comment by LavrovArtem** [comment] 2019-02-07 14:59
I've investigated this problem and figured out that a processed form action attribute has no iframe flag because there is no iframe with the 'result' name during a server processing.

<details>
<summary>Simplified server for reproducing</summary>

```js
require('http')
    .createServer((req, res) => {
        switch (req.url) {
            case '/':
                res.writeHead(200, { 'content-type': 'text/html' });
                res.end(`
                    <form target="result" action="/result"></form>
                    <div id="result"></div>
                    <button id="run">Run</button>
                    <script>
                        document.querySelector('#result').innerHTML = '<iframe name="result"></iframe>';
                        document.querySelector('#run').onclick = function () {
                            document.querySelector('form').submit();
                        };
                    </script>
                `);
                break;
            case '/result?':
                res.writeHead(200, { 'content-type': 'text/html' });
                res.end(`<h1>result iframe</h1>`);
                break;
            default:
                res.end();
        }
    })
    .listen(2222, () => console.log('http://localhost:2222/'));
```
</details>

**Comment by arubtsov** [comment] 2019-05-29 12:14
Same here: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_button_basic

**Comment by Dmitry-Ostashev** [comment] 2021-05-18 08:19
https://supportcenter.devexpress.com/internal/ticket/details/T991816

**Comment by AlexKamaev** [comment] 2021-08-02 13:00
> I've investigated this problem and figured out that a processed form action attribute has no iframe flag because there is no iframe with the 'result' name during a server processing.
> 
> Simplified server for reproducing

I created a separate issue for this scenario https://github.com/DevExpress/testcafe-hammerhead/issues/2675

**Comment by AlexKamaev** [comment] 2021-08-02 13:06
I could not reproduce the issue from the first post, so I closed this issue about 'fiddle.net'. 
I created separate issues for other cases discussed in this ticket.

**Closed by AlexKamaev** 2021-08-02 13:06 UTC
Labels: AREA: client, SYSTEM: URL processing, SYSTEM: iframe processing, TYPE: bug
