### ISSUE TITLE
Optional chaining rewriting by Hammerhead causes unhandled exception

### ISSUE THREAD

**Issue by lg-kialo** [DevExpress/testcafe-hammerhead#2858] opened 2023-02-23 16:14 UTC
### What is your Scenario?

We are testing our SPA with TestCafe and after changing our JS bundling code to target newer browsers, most of our tests are failing due to unhandled exceptions that crash the app.
After investigation we identified the root of the problem in how Hammerhead rewrites our Javascript.

More specifically given this input code:
```js
renderClaimFromSameDiscussionForDragImage() {
  const e = this.props.clipboardData?.location.id || this.props.effectiveLocationId;
}
```
Hammerhead transpiles it to
```js
renderClaimFromSameDiscussionForDragImage() {
  const e = __get$(this.props.clipboardData, 'location', true).id || this.props.effectiveLocationId;
}
```

During runtime, `this.props.clipboardData` is undefined, which would not be an issue for the original version, but the rewrite throws the `TypeError: __get$(...) is undefined` exception.

Looking at https://github.com/DevExpress/testcafe-hammerhead/issues/2714, it seems like support for optional chaining should be part of TestCafe already. So not sure what's happening here.

### What is the Current behavior?

Our tests fail due to Hammerhead rewriting the Javascript bundles

### What is the Expected behavior?

Hammerhead doesn't mess with our Javascript :) 

### What is your public website URL? (or attach your complete example)

See above

### What is your TestCafe test code?

It doesn't matter

### Steps to Reproduce

See above

### TestCafe version

2.2.0

### Command-line arguments

-

### Browser name(s) and version(s)

Firefox 110

### Platform(s) and version(s)

Ubuntu 22.04

### Other

`testcafe-hammerhead` version 28.2.5

**Comment by lg-kialo** [comment] 2023-02-23 16:21
I saw just now https://github.com/DevExpress/testcafe/issues/7387 and https://github.com/DevExpress/testcafe/issues/7424, I should try upgrading `testcafe-hammerhead` to the latest version first

**Comment by Aleksey28** [comment] 2023-02-24 06:56
Hi @lg-kialo,

I managed to reproduce the issue. We will update this thread once we have news.

As a workaround, you can use the [--experimental-proxyless](https://testcafe.io/documentation/404237/guides/experimental-capabilities/proxyless-mode) option. We are actively working on this mode.

**Comment by lg-kialo** [comment] 2023-02-27 08:35
> Hi @lg-kialo,
> 
> I managed to reproduce the issue. We will update this thread once we have news.
> 
> As a workaround, you can use the [--experimental-proxyless](https://testcafe.io/documentation/404237/guides/experimental-capabilities/proxyless-mode) option. We are actively working on this mode.

Thank you for looking into this. Unfortunately the proxyless mode does not suit us, we don't use Chrome because I think we have too many blinkers there

**Comment by Aleksey28** [comment] 2023-02-28 07:17
I see. The only thing I can suggest is to add an optional chaining operator to all properties after the first one. For example:
```js
this.props.clipboardData?.location?.id
```
It will help you for a while.

**Comment by bbutel** [comment] 2023-04-26 12:43
> I see. The only thing I can suggest is to add an optional chaining operator to all properties after the first one. For example:
> 
> ```js
> this.props.clipboardData?.location?.id
> ```
> 
> It will help you for a while.

Hi,

I have the same issue on my side.

Do you have a patch we could apply on hammerhead instead of your proposal to change our application on optional chaining management.

By the way, I cannot use proxyless mode because it seems that some breaking changes come with it (run does not work at all in proxyless mode on my side. I have no time to investigate)

Thx a lot

**Comment by bbutel** [comment] 2023-05-03 19:36
Thx for your answer.

I think it is the same issue.

Indeed, in original description, it is said that "this.props.clipboardData?.location.id" is transformed into __get$(this.props.clipboardData, 'location', true).id

In both cases, the transformation does not take care about the possibility that first parameter could be undefined and led to an exception instead of returning undefined as expected.

To me, it is an issue about the optional chaining management with hammerhead proxy.

So it would be great to have a fix to support all kind of optional chaining and not opening an issue each time we are facing to an unpexpected behavior.

thx a lot

**Comment by Aleksey28** [comment] 2023-05-08 07:06
JavaScript is permanently improving, that's why we cannot cover all cases once and forever. We improve `testcafe-hammerhead` behavior step by step with available resources.

Regarding your case, I don't understand which exactly unexpected behavior you faced. All that I tried with your example worked as expected in the browser. We can't just throw away this transpilation, because it is necessary for correct work testcafe-hammerhead, but we make it work as expected.

**Comment by bbutel** [comment] 2023-05-12 14:14
Thx a lot for your answer.
My issue is the same as mentionned by @lg-kialo

```ts
# e is undefined
e?.myObject[X] ?? 0 # return undeifned with optional chaining
# but hammerhead change that into 
__get$(e?.myObject, X) ?? 0 # here, an exception is raised. 
```

Here the patch to ugly solve my issue:
```ts
diff --git a/node_modules/testcafe-hammerhead/lib/client/hammerhead.js b/node_modules/testcafe-hammerhead/lib/client/hammerhead.js
index 2b7fea5..5e52241 100644
--- a/node_modules/testcafe-hammerhead/lib/client/hammerhead.js
+++ b/node_modules/testcafe-hammerhead/lib/client/hammerhead.js
@@ -4130,6 +4130,7 @@
 	    directive,
 	    extra;
 
+
 	var Syntax = {
 	    AssignmentExpression:     'AssignmentExpression',
 	    AssignmentPattern:        'AssignmentPattern',
@@ -21486,7 +21487,9 @@
 	    PropertyAccessorsInstrumentation._propertyGetter = function (owner, propName, optional) {
 	        if (optional === void 0) { optional = false; }
 	        if (isNullOrUndefined(owner) && !optional)
-	            PropertyAccessorsInstrumentation._error("Cannot read property '".concat(propName, "' of ").concat(inaccessibleTypeToStr(owner)));
+						// ugly fix for https://github.com/DevExpress/testcafe-hammerhead/issues/2858
+						return undefined
+	          //PropertyAccessorsInstrumentation._error("Cannot read property '".concat(propName, "' of ").concat(inaccessibleTypeToStr(owner)));
 	        if (typeof propName === 'string' && shouldInstrumentProperty(propName)) {
 	            if (optional && isNullOrUndefined(owner))
 	                return void 0;
```

thx a lot

**Comment by bbutel** [comment] 2023-05-15 08:48
thx a lot. Here the new issue: https://github.com/DevExpress/testcafe-hammerhead/issues/2891

**Comment by gg-kialo** [comment] 2024-03-18 13:33
The issue seems to be that the transformation treats `MemberExpression` in isolation in [property-get.ts](https://github.com/DevExpress/testcafe-hammerhead/blob/bade0f6e5483a9d595782b2e95fc148ea2a55ee6/src/processing/script/transformers/property-get.ts#L26). But `MemberExpression`s that are part of a `ChainExpression` ([estree docs](https://github.com/estree/estree/blob/master/es2020.md#chainexpression)) have semantics that should to be performed on the level of the `ChainExpression`.

In order to support the correct semantics of optional chaining, I think the transformed code will need to look like the output of how a transpiler would support optional chaining in old browsers.

**Comment by Bayheck** [comment] 2024-03-20 12:42
Hello,

The reported issue has a TestCafe workaround available when Native Automation is enabled. Due to this, the priority of this issue is relatively low. That means that we don’t have immediate plans to work on this task, and we'll be closing this issue.
 
However, if you'd like to contribute and have a solution in mind, feel free to create a pull request (PR) addressing this issue. We would appreciate any contributions and will gladly review any PRs submitted.
 
Thank you for your understanding and for your interest in improving our platform.

**Closed by Bayheck** 2024-03-20 12:42 UTC
Labels: TYPE: bug, STATE: Need response
