### ISSUE TITLE
`Authorization` header prefixed with `hammerhead|prefix|by-client` #2104

### ISSUE THREAD

**Issue by rssfrncsrenishaw** [DevExpress/testcafe-hammerhead#2192] opened 2019-12-03 08:49 UTC
Certain requests have a prefixed Authroization header value. The prefix is "hammerhead|prefix|by-client" and is causing requests to fail with 403s.

Related to resolved #2104  which does not state how/why it was resolved.

**Comment by Farfurix** [comment] 2019-12-04 12:04
@rssfrncsrenishaw 

Hello,

This issue is a duplicate of https://github.com/DevExpress/testcafe/issues/4474#issuecomment-553401933.

**Closed** 2019-12-04 12:05 UTC
Labels: REASON: duplicate, TYPE: question
