### ISSUE TITLE
Hammerhead.js typerror makes website crash

### ISSUE THREAD

**Issue by esbarila** [DevExpress/testcafe-hammerhead#2859] opened 2023-02-28 17:13 UTC
### What is your Scenario?

Navigate to dev.remo.co

### What is the Current behavior?

TypeError: Cannot read properties of undefined (reading 'ondevicechange')

It makes the app crash, can't start tests.

### What is the Expected behavior?

should get to the Login screen.

### What is your public website URL? (or attach your complete example)

https://dev.remo.co

### What is your TestCafe test code?

fixture('Signup').page("https://dev.remo.co/");

### Your complete configuration file

none yet

### Screenshots

![Screenshot from 2023-02-28 13-48-51](https://user-images.githubusercontent.com/47305731/221926647-e04334a9-4f3f-45f4-853b-5111f61e3e7f.png)

### Steps to Reproduce

1. Navigate to https://dev.remo.co

### TestCafe version

2.1.0

### Node.js version

v14.18.2

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

chrome 110

### Platform(s) and version(s)

Linux Ubuntu 22.04.2

**Comment by Aleksey28** [comment] 2023-03-02 09:07
Hi @esbarila

I managed to reproduce the issue. As a workaround, try using the [Proxyless Mode](https://testcafe.io/documentation/404237/guides/experimental-capabilities/proxyless-mode). We are actively working on this mode.

**Comment by esbarila** [comment] 2023-03-02 11:31
@Aleksey28 Thanks for the update! The proxyless mode doesn't seem to help though.

**Comment by Aleksey28** [comment] 2023-03-03 08:49
I opened this page in `proxyless` mode and got no errors. Please describe why `proxyless` mode didn't help you.

**Comment by esbarila** [comment] 2023-03-03 22:37
> I opened this page in `proxyless` mode and got no errors. Please describe why `proxyless` mode didn't help you.

Im still getting the same error as original, Im running the test like this `testcafe chrome tests/test.js --experimental-proxyless`
Also added a testcaferc.json file with the experimentalProxyless config to true but no chance.

**Comment by miherlosev** [comment] 2023-03-07 09:00
Hi @esbarila,

As far as I understand, the issue is resolved by using the `experimentalProxyless` option. If you need to run tests in other browsers, please reopen this issue.

**Closed by miherlosev** 2023-03-07 09:01 UTC
Labels: TYPE: bug
