### ISSUE TITLE
Requests to https://sdk.split.io/ fails

### ISSUE THREAD

**Issue by DzmVasileusky** [DevExpress/testcafe-hammerhead#2360] opened 2020-06-23 13:18 UTC
### What is your Scenario?

Add split.io integration to a website.
```
<script src="//cdn.split.io/sdk/split-10.12.1.min.js"></script>
<script>
// Instantiate the SDK. CDN will expose splitio globally 
var factory = splitio({ 
  core: {
    authorizationKey: 'YOUR_API_KEY',
    // your internal user id, or the account id that 
    // the user belongs to. 
    // This coudld also be a cookie you generate
    // for anonymous users
    key: 'key',
    // an OPTIONAL traffic type, if provided will be
    // used for event tracking with the SDK client.
    trafficType: 'A_TRAFFIC_TYPE'
  }
});
// And get the client instance you'll use
var client = factory.client();
</script>
```
 
### What is the Current behavior?

Requests to sdk.split.io return 400 error
Request headers
```
GET /BFd0v8wi1/https://sdk.split.io/api/splitChanges?since=-1 HTTP/1.1
Host: localhost:61071
Connection: keep-alive
accept: application/json
authorization: Bearer privateapikey
splitsdkversion: javascript-10.12.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
x-hammerhead-credentials: same-origin
x-hammerhead-origin: http://www.crexi.local:4200
content-type: application/json
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:61071/BFd0v8wi1/http://www.crexi.local:4200/lease/properties
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
```
The same headers are working well for 
https://sdk.split.io/api/splitChanges?since=-1
And not working for 
http://localhost:61071/BFd0v8wi1/https://sdk.split.io/api/splitChanges?since=-1

Also it's working well when I'm testing our production domain www.crexi.com, but not working in case of localhost domain: localhost: www.crexi.local:4200
 
### What is the Expected behavior?

No request error
 
### What is your public web site URL?

Your website URL (or attach your complete example): 
www.crexi.com/lease/properties

### Your Environment details:

* node.js version:                    v12.16.1
* browser name and version: Chrome 83
* platform and version:         macOS 10.14, Windows 10

**Comment by LavrovArtem** [comment] 2020-06-23 21:15
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/2344

**Closed by LavrovArtem** 2020-06-23 21:15 UTC
Labels: REASON: duplicate, STATE: Need response
