### ISSUE TITLE
Uncaught exception: socket has been ended by the other party

### ISSUE THREAD

**Issue by Arthy000** [DevExpress/testcafe-hammerhead#2445] opened 2020-08-21 13:17 UTC
Hello!

I implemented a runner for the project I'm working on using the TestCafe API.
With my coworkers, we noticed that some tests started failing after we upgraded NodeJS past version 10.15.3
(basically, no problem with 10.15.3 or below, but anything newer and we get the issue described here)

We randomly receive the following error:
```
× Scenario: Successful registration process (single step)
   1) Uncaught exception:
      Error: This socket has been ended by the other party
      at TLSSocket.writeAfterFIN [as write] (net.js:407:14)
      at Socket.ondata (_stream_readable.js:713:22)
      at Socket.emit (events.js:200:13)
      at Socket.EventEmitter.emit (domain.js:471:20)
      at addChunk (_stream_readable.js:294:12)
      at readableAddChunk (_stream_readable.js:275:11)
      at Socket.Readable.push (_stream_readable.js:210:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
      Browser: Chrome 84.0.4147.125 / Windows 10
```
Otherwise, the test itself does not have any reason to fail (one test will be fine for several runs, then fail with that error - and only that error)

I manage to trigger it by chaining a lot of navigateTo to our website.
=> I usually get a few fails out of 10 identical tests (see the test code)

My investigation so far shows that it seems to be linked to our usage of WebSocket.
The issue **only happens with Chrome**, but we want coverage of all browsers (plus Firefox seems to not always close properly but that's an issue for another time)
**Downgrading NodeJS solves the issue** but the rest of the project now relies on a newer version, meaning we have to switch back and forth, which is not ideal.

I'm not sure you will have access to the website in the example - it is protected against access out of belgium. I might be able to arrange something if needed.
I've reproduced the issue with another website (a completely different front-end, that we started from scratch so it does not have much in common with the current site)
I was NOT able to reproduce the issue with external websites that use WebSocket (again, we might have a heavier load on the WS than the websites I tried)
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
https://www.circus.be
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture`Test the runner`;

test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
```
</details>
 
### Your Environment details:
 
* testcafe version:  1.9.1                 
* node.js version:   12.18.3                 
* browser name and version: Chrome 84 
* platform and version:   Windows 10       

[report.zip](https://github.com/DevExpress/testcafe/files/5108979/report.zip)

**Comment by Farfurix** [comment] 2020-09-25 07:49
@Arthy000

Hello,

I tried to research your website but faced the "connection failure" issue again. It is not possible to debug your code due to this: only one try out of dozens is successful. Feel free to reopen the issue once you can fix this unstable connection.

**Comment by Arthy000** [comment] 2020-09-28 06:50
Hello, 

I don't know why, it never even occurred to me to that we have other websites in other countries.
I had one of my coworkers confirm that we can reproduce the issue on circus.es (Spain website)

Hopefully the connection will be more stable, as it (legally) can be reached from outside of Spain.

Regarding the test code, it's the same as before but with circus.es instead of circus.be

**Comment by Farfurix** [comment] 2020-09-29 11:11
@Arthy000 

Hello,

I reproduced the issue with the https://www.circus.es website address. Our team will examine it and will check for a suitable solution.

For the team:
It can be reproduced by manually reloading the page using `http-playground`:
![Capture](https://user-images.githubusercontent.com/30019338/94539442-e5701f80-024d-11eb-838c-a3784d115d2e.PNG)

Or, we can use the following TestCafe test:

```js
fixture `Fixture`
    .page `https://www.circus.es`;

test('test', async t => {
    await t.eval(() => location.reload(true));

    await t
       .wait(5000)
       .expect(true).ok();

    await t.eval(() => location.reload(true));

    await t
        .wait(5000)
        .expect(true).ok();
});
```
![Capture](https://user-images.githubusercontent.com/30019338/94539736-4e579780-024e-11eb-827d-71cfe860f597.PNG)

**Comment by Arthy000** [comment] 2020-12-21 10:06
Hello, it's been a while, do you have any news regarding this issue?

**Comment by Farfurix** [comment] 2020-12-22 07:33
@Arthy000 

Hello,

No updates yet. We plan to research this issue, but I cannot give you any time frames as to when the issue will be resolved.

**Comment by janrozycki** [comment] 2021-02-24 16:29
I'm experiencing the same issue. Do we have any updates on when it might be resolved?

**Comment by Farfurix** [comment] 2021-02-25 08:36
@Arthy000 @janrozycki

Hello,

I checked [this scenario](https://github.com/DevExpress/testcafe-hammerhead/issues/2445#issuecomment-700633728) with TestCafe v1.11.0 and confirm that the issue persists, but it does not occur regularly:
![Capture](https://user-images.githubusercontent.com/30019338/109119844-439a2380-7756-11eb-80b1-d6bbbe543155.PNG)

Also, I see that a WebSoket error is thrown in the same "page reload" scenario without TestCafe:
![Capture1](https://user-images.githubusercontent.com/30019338/109121490-5a417a00-7758-11eb-9e9f-c54f36141b48.PNG)

I recommend you resolve this WebSoket issue on your side and share your result with us.

**Comment by Arthy000** [comment] 2021-02-26 13:17
Hi @Farfurix 

To be honest I'm lost.
When I test our newest website (that uses a completely different front), the issue also happens. 

However, in the logs of the browser there doesn't seem to be any specific issue that appears after each `socket has been ended by the other party` (I used debug-on-fail and the fails seem to be completely random in regards to the logs)

What really bothers me is that changing our NodeJS version (10.15.3 or lower) seems to fix the issue. I cannot think of any scenario where changing the local version of Node would fix the issue of the website (hosted somewhere else)

Also, I don't know about @janrozycki, but I never got the WS issue you mention in your last post (even on the same website).

**Comment by Farfurix** [comment] 2021-03-01 08:05
@Arthy000 

Hello,

I checked it again and wasn't able to reproduce the WebSoket (without TestCafe), and the following test passed without errors:
```js
fixture`Test the runner`;

test('Basic V3 test', async (t) => {
    await t.navigateTo('https://www.circus.es').wait(5000);
});
test('Basic V3 test', async (t) => {
    await t.navigateTo('https://www.circus.es').wait(5000);
});
test('Basic V3 test', async (t) => {
    await t.navigateTo('https://www.circus.es').wait(5000);
});
test('Basic V3 test', async (t) => {
    await t.navigateTo('https://www.circus.es').wait(5000);
});
test('Basic V3 test', async (t) => {
    await t.navigateTo('https://www.circus.es').wait(5000);
});
test('Basic V3 test', async (t) => {
    await t.navigateTo('https://www.circus.es').wait(5000);
});
test('Basic V3 test', async (t) => {
    await t.navigateTo('https://www.circus.es').wait(5000);
});
test('Basic V3 test', async (t) => {
    await t.navigateTo('https://www.circus.es').wait(5000);
});
test('Basic V3 test', async (t) => {
    await t.navigateTo('https://www.circus.es').wait(5000);
});
test('Basic V3 test', async (t) => {
    await t.navigateTo('https://www.circus.es').wait(5000);
});

```
Result:
![Capture](https://user-images.githubusercontent.com/30019338/109463004-60479b80-7a75-11eb-9db3-1f857dceb738.PNG)

My setup: Windows 10, Node.js v14.15.4, TestCafe v1.11.0, Chrome 88.

I believe that the "This socket has been ended by the other party" error relates to [the WebSoket error I faced before without TestCafe](https://github.com/DevExpress/testcafe-hammerhead/issues/2445#issuecomment-785719902) and thus this error should be fixed on the website side. I'll close the issue.

@janrozycki 

Hello,

If your scenario doesn't relate to the @Arthy000 tested website, I recommend you create [a new issue](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md) with a simple reproducible example.

**Closed by Farfurix** 2021-03-01 08:05 UTC
Labels: AREA: server, FREQUENCY: level 1, STATE: Need response, SYSTEM: pipeline, TYPE: bug
