### ISSUE TITLE
Test Execution hanging and restarting execution as hammerhead keeping assets requests in pending state for long time

### ISSUE THREAD

**Issue by lokender88** [DevExpress/testcafe-hammerhead#1887] opened 2018-12-11 16:15 UTC
### What is your Test Scenario?
Requesting for page url load and added waitForLoad with some expected locator and text visibility. But I still see that some of the assets requests are in pending state for long time in Network console which is initiated by hammer head. Due to this my test are hanging in the middle of somewhere and not moving forward with further steps.

Even I verified same page url manually and all assets requests are loading properly without any issues when we hit same url manually in browser.

**Note:** Same test scenarios was executing perfectly in Firefox 63.0 browser.
 
### What is the Current behavior?
Test Execution hanging and restarting execution as hammerhead keeping assets requests in pending state for long time
 
### What is the Expected behavior?
Assets request should not keep in pending status. 
 
<summary>**Screenshots:**</summary>

<img width="639" alt="screen shot 2018-12-11 at 12 53 14 pm" src="https://user-images.githubusercontent.com/5803509/49814197-e4ec5900-fd47-11e8-9083-1a58d87ff469.png">

</details>

### Your Environment details:
 
* testcafe version:                   0.23.3-alpha.1 and 0.23.3
* node.js version:                    v8.12.0
* command-line arguments:  testcafe chrome -e mytest.js
* browser name and version: Chrome 70, Safari12
* platform and version:          macOS 10.14
* other:                                   same test execution was works fine with Firefox 63 versions.

**Comment by lokender88** [comment] 2019-01-09 13:59
@AndreyBelym & Team, Did we find the solution for it?. Can we prioritize this as it's blocking cross browser test executions?.

**Comment by LavrovArtem** [comment] 2019-01-10 12:11
@lokender88, We need additional time to investigate this problem. After that, we'll add it to the current sprint.

**Comment by Avinger27** [comment] 2019-04-29 06:17
@lokender88 @AndreyBelym Ran into this problem today. I can workaround this for now, but has this been resolved?

**Comment by miherlosev** [comment] 2019-04-29 11:11
@lokender88
The problem has been fixed in the `testcafe@1.1.3` version.
 
@Avinger27
It looks like a separate issue. Please try to run your tests using the latest TestCafe version (1.1.3).
If the problem still persists, please provide a simple example where we can reproduce the problem on our side.

**Closed by miherlosev** 2019-04-29 11:11 UTC
Labels: STATE: Need response, TYPE: bug
