### ISSUE TITLE
CORS issue with 403 during test execution 

### ISSUE THREAD

**Issue by shyedhu** [DevExpress/testcafe-hammerhead#2565] opened 2021-01-22 16:38 UTC
Steps to Reproduce:
Clone the https://github.com/javenkn/testcafe-poc repository and make sure update latest testcase v1.10.2-alpha.1 on package.json file before running below the npm commands(since our current package.json file having old testcafe version)
Run the npm install command
Run the test script from package.json file

it throws CORS issue with 403 error code while running the test

Your Environment details:
node.js version: v12.18.0
browser name and version: Chrome 87.0.4280.88
platform and version: macOS 10.15.6

**Comment by shyedhu** [comment] 2021-01-22 16:39
How can we avoid 403 error code while running testcafe run?

**Comment by Farfurix** [comment] 2021-01-25 09:43
@shyedhu 

Hello,

I cannot reproduce the "403" error with this example (Chrome 88, Windows 10, macOS 10.15.5). I only see the following error:
```
1) AssertionError: expected false to be truthy
...
         37 |  // check that order summary exists
       > 38 |  await t.expect(Selector('div[data-attr="cart-total"]').exists).ok();
```

This element doesn't exist on the page without TestCafe:
```
> document.querySelector('div[data-attr="cart-total"]')
< null
```

Could you please modify your example so we can see the "403" error?

**Comment by shyedhu** [comment] 2021-01-25 16:03
> @shyedhu
> 
> Hello,
> 
> I cannot reproduce the "403" error with this example (Chrome 88, Windows 10, macOS 10.15.5). I only see the following error:
> 
> ```
> 1) AssertionError: expected false to be truthy
> ...
>          37 |  // check that order summary exists
>        > 38 |  await t.expect(Selector('div[data-attr="cart-total"]').exists).ok();
> ```
> 
> This element doesn't exist on the page without TestCafe:
> 
> ```
> > document.querySelector('div[data-attr="cart-total"]')
> < null
> ```
> 
> Could you please modify your example so we can see the "403" error?

Hi @Farfurix .

Thanks for your quick response ! I just created new repo with required fix and also updated testcafe v1.10.2-alpha.1 in package.json file , Now i'm able to reproduce 403 error code during testcafe execution on both windows and mac system, Can you please help to check below the new repo and let me know .Thanks in advance ! 

`https://github.com/shyedhu/testcafe-poc/blob/main/README.md`

**Comment by shyedhu** [comment] 2021-01-25 16:08
Hi @Farfurix , Here's updated repo for reproduce that 403 error code during testcafe execution

https://github.com/shyedhu/testcafe-poc/blob/main/README.md

**Comment by Farfurix** [comment] 2021-01-26 07:15
@shyedhu 

Hello,

I followed your steps. I checked this scenario **without TestCafe** and got the same CORS error you mentioned above in your report:
```
Access to fetch at 'https://api.nike.com/buy/checkout_previews/v3/2a16f851-d25e-4801-84c8-6b4cb18d14c6' from origin 'https://www.nike.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
![Untitled-2](https://user-images.githubusercontent.com/30019338/105811097-25a59b80-5fbd-11eb-88e7-e482e78d9f89.jpg)

So, it is not related to TestCafe. I'll close this issue.

**Closed by Farfurix** 2021-01-26 07:15 UTC
Labels: STATE: Need response

**Comment by shyedhu** [comment] 2021-01-28 02:44
> @shyedhu
> 
> Hello,
> 
> I followed your steps. I checked this scenario **without TestCafe** and got the same CORS error you mentioned above in your report:
> 
> ```
> Access to fetch at 'https://api.nike.com/buy/checkout_previews/v3/2a16f851-d25e-4801-84c8-6b4cb18d14c6' from origin 'https://www.nike.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> ```
> 
> ![Untitled-2](https://user-images.githubusercontent.com/30019338/105811097-25a59b80-5fbd-11eb-88e7-e482e78d9f89.jpg)
> 
> So, it is not related to TestCafe. I'll close this issue.

@Farfurix 
 I tried same steps through manually in my windows 8.1+chrome Version 87.0 without TestCafe,In fact i'm able to see success 202 expected response code in network log , please find attached the screenshot for your reference,
![success status code 202 during manually](https://user-images.githubusercontent.com/8210719/106082337-5970e600-60cf-11eb-8887-02531cd7fb8c.png)

 i'm not sure which tool/framework you were able to reproduce the same CORS issue on your machine., now the problem with testcafe only..Is there is option to fix the CORS issue in testcafe , how do we pass `access-control-allow-origin: https://www.nike.com` in Custom Request Hook class?

**Comment by Farfurix** [comment] 2021-01-28 08:29
@shyedhu 

Hello,

I got the same error (one of "api.nike.com" requests has a CORS error) in the Windows environment without using TestCafe. So, I can't say that there is an issue on our side. The CORS issue needs to be fixed in the application code.

Windows 10 / Chrome 88:
![Untitled-2](https://user-images.githubusercontent.com/30019338/106101253-aea00c80-614e-11eb-99ec-2e4eec14c9ae.jpg)
```
Access to fetch at 'https://api.nike.com/buy/checkout_previews/v3/e95402b7-cba3-4706-ac65-ab973092964e' from origin 'https://www.nike.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
