### ISSUE TITLE
'Can't execute code from a freed script' error for document.write in iframe with same-domain src

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#384] opened 2016-01-29 16:02 UTC
Test for reproduce:
```javascript
   var iframe = document.createElement('iframe');
    var src    = window.QUnitGlobals.getResourceUrl('index.html');

    iframe.id = 'test_ojfnnhsg43';
    iframe.setAttribute('src', src);
    window.QUnitGlobals.waitForIframe(iframe)
        .then(function () {
            var iframeDocument = iframe.contentDocument;
            
            iframeDocument.write('<h1>test</h1>'); //this line throws the error
            
            iframe.parentNode.removeChild(iframe);
            start();
        });
    document.body.appendChild(iframe);
```

```javascript
index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <script src="/hammerhead.js" class="script-hammerhead-shadow-ui"></script>
</head>
<body>
    <script type="text/javascript">
        var hammerhead = window['%hammerhead%'];

        hammerhead.get('./utils/destination-location').forceLocation('http://localhost/sessionId/http://subdomain.example.com');
        hammerhead.start({
            sessionId: 'sessionId',
            CROSS_DOMAIN_PROXY_PORT: 2000
        });
    </script>
    <a href="/index.html">/index.html</a>
</body>
</html>
```

Only in IE and Edge.

**Comment by miherlosev** [comment] 2016-01-29 16:29
I'm working on this

**Comment by churkin** [comment] 2016-04-18 13:39
Maybe it's a duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/525?

**Comment by miherlosev** [comment] 2016-04-18 15:19
Probably. I will check it after fix #525

**Comment by miherlosev** [comment] 2016-04-20 07:54
Origin bug is dublicate of #525.
But in IE (I check in IE11) 'Permission denied' script error occurs.
It is raised inside DocumentWriter.
@LavrovArtem  please, investiagate it.

**Comment by LavrovArtem** [comment] 2016-04-20 07:58
I'm working on this

**Comment by LavrovArtem** [comment] 2016-04-26 14:14
In IE after [write](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/document/index.js#L48) we can not call any function. If we remove [this code](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/document/index.js#L51)
```javascript
            this.nodeSandbox.mutation.onDocumentCleaned({
                window:             this.window,
                document:           this.document,
                isIframeWithoutSrc: isIframeWithoutSrc
            });
```
and [this](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/document/index.js#L59)
```javascript
        this.nodeSandbox.processNodes(null, this.document);
```
then error is not occured, but if we add `console.log('hello')` after write, then error is occured.

**Closed** 2016-06-06 13:40 UTC
Labels: AREA: client, BROWSER: Edge, BROWSER: IE10, BROWSER: IE11, BROWSER: IE9, TYPE: bug
