### ISSUE TITLE
Script errors for http://www.freelancer.com/

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#668] opened 2016-07-08 09:08 UTC
see [video](http://screencast.com/t/PdbHuVTdFDy) for reproduce.

**Comment by miherlosev** [comment] 2016-07-13 08:34
I'm working on this.

**Comment by miherlosev** [comment] 2016-07-13 12:39
Site using SystemJS module loader (https://github.com/systemjs/systemjs). 
Module loader uses path '/' for module loading.
We calculate wrong url for modules.
Simple example in progress...

**Comment by miherlosev** [comment] 2016-07-14 11:45
Site performs xhr request to the cross-domain url - `https://cdn2.f-cdn.com/build/modules/login-signup-be79c24bec357faaeb956cc7ab5bb12a.js`.
On first request the server respond the `Access-Control-Allow-Origin` header, but on second and next requests the server doesn't respond `Access-Control-Allow-Origin` header. 
But this header is getting from browser cache and request pass CORS and performs without errors. 
See image from Firebug:
![Firebug console](https://cloud.githubusercontent.com/assets/4133518/16838339/5649d69a-49d1-11e6-92f6-00b171d74ec6.png)

So hammerhead doesn't cache responce headers and request doesn't pass CORS and finished with error.

**Comment by LavrovArtem** [comment] 2016-07-14 11:48
I'm think it duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/617

**Comment by miherlosev** [comment] 2016-07-14 12:50
Yes. It is.

**Closed** 2016-07-14 12:50 UTC
Labels: !IMPORTANT!, AREA: client, TYPE: bug
